### ISSUE TITLE
Animated zoom

### ISSUE THREAD

**Issue by payzoff** [ariutta/svg-pan-zoom#101]
Hi, 
Is there a way to make animated zooming?

Thanks

**Comment by bumbu** [comment]
Currently such functionality is not supported. You could do it 2 ways:
- Use a twin library (or write you own function) and just call zoom multiple times. This may be slow but it is possible to be implemented now.
- Use SVG [animateTranform](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform) element. It seems to be the right way. But it need some more work to be done. 

You can actually try to implement second solution by listening to zoom events, canceling them and adding animateTranform manually to the SVG. When your animation is done, call zoom again but this time don't cancel it (necessary to update library inner state).

If you get a working result - please share it here, it is really interesting to se a solution for this problem.

**Comment by bumbu** [comment]
I added an example of how pan can be animated. You can find it in `demo/simple-animation`.
The same can be used for zooming.

**Comment by mparpaillon** [comment]
I've added a CSS transition to `svg-pan-zoom_viewport` like this:

```css
.svg-pan-zoom_viewport {
    transition: transform 0.5s ease;
}
```

and changed line 151 in the `svg-utilities.js` file by

```js
element.style.transform = s;
```

Feels better

I will fork the repo to add this.

Now the zoom and the pan are animated with the easing I want
