### ISSUE TITLE
Pan in scale mode

### ISSUE THREAD

**Issue by vsug1024** [ariutta/svg-pan-zoom#102]
The issue lies in paning the image after scaling as it does not take in consideration the mouse delta position.

May be this code would help to fix it:
svg-pan-zoom/dist/svg-pan-zoom.js (line 1351):
from:
```javascript
...
, s = 'matrix(' + matrix.a + ',' + matrix.b + ',' + matrix.c + ',' + matrix.d + ',' + matrix.e + ',' + matrix.f + ')';
...
```
to:
```javascript
...
 , s = 'matrix(' + matrix.a + ',' + matrix.b + ',' + matrix.c + ',' + matrix.d + ',' + matrix.e/element.parentElement.currentScale + ',' + matrix.f/element.parentElement.currentScale + ')';
...
```

Thanks,
Mike

**Comment by bumbu** [comment]
Ho you mean zooming by scaling? Or it is some other scaling (like browser zooming)?
Can you please create a jsfiddle example with this issue?

**Comment by vsug1024** [comment]
Sorry for my english. I meant 'pan' as 'move', but not as 'zoom'. Read the topic as 'Moving in scale mode'.
I could not reproduce it on jsfiddle because the error "Uncaught TypeError: Cannot read property 'documentElement' of null" in the line "svg = element.contentDocument.documentElement;" of the library.
I found that my problem reproduced only for my svg file. I will investigate the problem further.
Thanks, 
Mike
