### ISSUE TITLE
Support for FF17

### ISSUE THREAD

**Issue by xie-qianyue** [ariutta/svg-pan-zoom#103]
I have a question : do you support FF version 17.0.5 ?

I have this error when loading :  
[10:35:49,959] NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMSVGMatrix.a] @ http://pathOfProject/svg-pan-zoom.js:406

As the log shows, it gets this error in the line 406. In the function `ShadowViewport.prototype.processCTM`. 
In detail, it break in this line :  
`newCTM.a = newScale; //x-scale`  

Because FF17 is a so old version, I would like to know whether you support it. If yes, could this issue be a bug?

**Comment by bumbu** [comment]
Hi,

We support only latest version of FF.
We had some code to support a bug up to FF33, but it was removed with #79. From my experience FF has many bugs with SVG in older versions, and it would be a mess to support all of them.

**Comment by xie-qianyue** [comment]
Thank you for your answer !
