### ISSUE TITLE
Probem occurs in loading - FF version 36.0.4

### ISSUE THREAD

**Issue by xie-qianyue** [ariutta/svg-pan-zoom#104]
I have this error when loading :

TypeError: Value being assigned to SVGMatrix.a is not a finite floating-point value.

in the line 406 of svg-pan-zoom.js.

**Comment by bumbu** [comment]
Can you please provide more details:
- What version of the library you use
- Live example of the code you use to initialize your SVG (you can use jsfiddle)
- An example of SVG

**Comment by xie-qianyue** [comment]
I've found the problem, because I called the destroy method `svgPanZoom('#schemaCartoSVG').destroy(); ` but it hasn't been initialized.
So another question comes, how can I check whether the svgPanZoom is created or not? I have to load it dynamic, so I need to destroy it.

**Comment by bumbu** [comment]
When you call `svgPanZoom('selector')` you initialize the library and get an instance to API object.
Now I would suggest keeping that instance in a variable `var svgPanZoomInstance = svgPanZoom('selector')` and checking against it.

When you destroy that instance you can assign `null` to your variable.

And then just check against that variable if you have an instance or not.

**Comment by xie-qianyue** [comment]
Thank you. It works !
