### ISSUE TITLE
NS_ERROR_FAILURE in Firefox

### ISSUE THREAD

**Issue by arvinsim** [ariutta/svg-pan-zoom#105]
I have somewhat the same problem with the other guy.

I am using version 3.1.1
I get an `NS_ERROR_FAILURE` error on line 361 in the unminified version of the file. This only
happens in Firefox only and not in Chrome.

    ...
        // Force updating CTM
        this.updateCTMOnNextFrame()

        this.options.svg.removeAttribute('viewBox')
    } else {
        var bBox = this.viewport.getBBox(); // <-- error is triggered here.

        // Cache viewbox sizes
        this.viewBox.x = bBox.x;
        this.viewBox.y = bBox.y;
        this.viewBox.width = bBox.width
        this.viewBox.height = bBox.height
    ...

This [fiddle](http://jsfiddle.net/sym3tri/kWWDK/) might be a clue on what is going on.

**Comment by bumbu** [comment]
Thanks for this bug report but from what I can see it is not related to svg-pan-zoom library.

From what I found there are similar reports on bugzilla.mozilla.org. Some of them are related to this error when element is not displayed `display="none"`. Now I don't see why you would wont to have your viewport hidden. The sole reason of viewport is to interact with it.

Maybe you want to achieve something specific that may be done in some other way?

p.s. You should be able to safely update to 3.1.3 (3.1.2 contains a bug fix for Firefox). There are no breaking changes from 3.1.1 to 3.1.3

**Comment by arvinsim** [comment]
After further investigation, you are right. I styled the root attribute to `overflow:hidden;` and it is probably the cause of this error.
