### ISSUE TITLE
Not able to center image in svg file, inside the viewbox

### ISSUE THREAD

**Issue by jportnov** [ariutta/svg-pan-zoom#106]
I am using the load dynamic svg example.   I need to load an image in the top left corner and/or center it in the viewbox.   I have not been able to do it by changing the x and y coordinates and by using center:true option during initialization.   I think there may be a bug, unless someone knows of settings that I am not using.

**Comment by bumbu** [comment]
Please provide a jsfiddle example.
Then I'll reopen the issue.
