### ISSUE TITLE
Changing SVG source via  <object> data attribute disables all features

### ISSUE THREAD

**Issue by Seiifer** [ariutta/svg-pan-zoom#107]
Hello there,
First, thanks for your awesome work.

I'm having some troubles with some behaviour I would like my application to have :

For example, I'm displaying my SVG using the `<object>` like this :
```html
<body ng-keypress="handleKeys($event)" ng-controller="viewerController">

<object id="svgElement" type="image/svg+xml" data="../SVG/map1.svg">
It seems your browser doesn't support SVG.
</object>
```
I set my options like this :
```html
<script>
    window.onload = function() {
        document.getElementById("svgElement").style.width = window.screen.availWidth + "px";
        document.getElementById("svgElement").style.height = window.screen.availHeight + "px"; // This seems to include the browser bar :(
        svgPanZoom('#svgElement', {
            zoomEnabled: true,
            controlIconsEnabled: true,
            fit: true,
            center: true,
            minZoom: 0.8,
            maxZoom: 30,
            zoomScaleSensitivity: 0.15,
            dblClickZoomEnabled: true
        });
    };
</script>
```
(Btw what do you suggest to use here instead of onload event ?)
It is working just fine. I can zoom and pan.

But depending on some events, I want to change the displayed SVG.
In my controller (I'm using AngularJS) I have this : 
```javascript
$scope.handleKeys = function(e) {
        if (window.event)
            $scope.keyPressed = window.event.keyCode;
        else if (e)
            $scope.keyPressed = e.which;
        // S key pressed :
        if ($scope.keyPressed == 83 || $scope.keyPressed == 115)
            alert("S key has been pressed"); // This will display the search banner on the top of the screen
        // C key pressed :
        if ($scope.keyPressed == 99 || $scope.keyPressed == 67) {
            document.getElementById("svgElement").data = "../SVG/map2.svg";
            document.getElementById("svgElement").style.width = window.screen.availWidth + "px";
            document.getElementById("svgElement").style.height = window.screen.availHeight + "px";
            svgPanZoom('#svgElement', {
                zoomEnabled: true,
                controlIconsEnabled: true,
                fit: true,
                center: true,
                minZoom: 0.8,
                maxZoom: 30,
                zoomScaleSensitivity: 0.15,
                dblClickZoomEnabled: true
            });
        }
    }
```
So it's half working :
When I press the 'C' Key, my new SVG is displayed instead of the old one (even if when I'm spamming the key the SVG disappear)
The main problem is : I lost the zoom, the pan, the width/height I had set... Basically I have nothing left on the new SVG.

Do you know why and how to fix it ?
Also could you please have a look at this : http://stackoverflow.com/questions/29372738/svg-as-zoomable-background-cant-select-anything

Best regards.

**Comment by bumbu** [comment]
Normally I would not answer it here (but on stackoverflow as mentioned in readme).

> (Btw what do you suggest to use here instead of onload event ?)

It depends on what you have. onload is fine if you have just one onload. If you use Angular then you have jQuery, so it is more safe to use jQuery onload callback `$(function(){//code goes here});

If you load your SVGs via a link (data attribute of the object) then you may want to wait for SVG to load ([an example with embed in demos](https://github.com/ariutta/svg-pan-zoom/blob/master/demo/dynamic-load.html)).

If you want to change SVG image then I would recomend:
* Cache/save actual svg-pan-zoom zoom and pan values
* Destroy actual svg-pan-zoom instance (use destroy API method)
* Update your object
* Initialize new svg-pan-zoom
* Set cached/saved pan and zoom values to new svg-pan-zoom instance
