### ISSUE TITLE
Issue with Chrome and IE

### ISSUE THREAD

**Issue by Seiifer** [ariutta/svg-pan-zoom#109]
Hello there,

I'm having some weird issues with Chrome and IE. My app works on firefox only at the moment : 

Here is the error I got in console with Chrome : 
```console
Uncaught TypeError: this.options.svg.createSVGMatrix is not a function
ShadowViewport.getCTM @ svg-pan-zoom.js:367
ShadowViewport.processCTM @ svg-pan-zoom.js:277
ShadowViewport.init @ svg-pan-zoom.js:207
ShadowViewport @ svg-pan-zoom.js:179
module.exports @ svg-pan-zoom.js:501
SvgPanZoom.init @ svg-pan-zoom.js:556
SvgPanZoom @ svg-pan-zoom.js:512
svgPanZoom @ svg-pan-zoom.js:1285
window.onload @ viewerController.js:182
```

This is the corresponding lines of the error : 
```javascript
    ShadowViewport.prototype.getCTM = function() {
        var safeCTM = this.options.svg.createSVGMatrix() // line 367
   //     var safeCTM = new Object()
        // Copy values manually as in FF they are not itterable
        safeCTM.a = this.activeState.zoom
        safeCTM.b = 0
        safeCTM.c = 0
        safeCTM.d = this.activeState.zoom
        safeCTM.e = this.activeState.x
        safeCTM.f = this.activeState.y

        return safeCTM
    }
```

So I tried to initialize the variable safeCTM as an object manuelly instead of calling createSVGMatrix(), since every values are set in the function anyway (I think).
But when I do that I get this error instead : 
```console
Error: Invalid value for <g> attribute transform="matrix(Infinity,0,0,Infinity,NaN,NaN)"
module.exports.setCTM @ svg-pan-zoom.js:1446
ShadowViewport.updateCTM @ svg-pan-zoom.js:494
module.exports.proxy @ svg-pan-zoom.js:1763
```

Now the error with IE : 
```console
SCRIPT5007: Unable to get the value of the property  « documentElement » : null or undefined object
svg-pan-zoom.js, line 1737 character 21
```

And the corresponding code : (I put the whole function to give a more accurate idea of where this is, the line causing the error has a comment with the number of the line)
```javascript
, getSvg: function(elementOrSelector) {
            var element
                , svg;

            if (!this.isElement(elementOrSelector)) {
                // If selector provided
                if (typeof elementOrSelector === 'string' || elementOrSelector instanceof String) {
                    // Try to find the element
                    element = document.querySelector(elementOrSelector)

                    if (!element) {
                        throw new Error('Provided selector did not find any elements. Selector: ' + elementOrSelector)
                        return null
                    }
                } else {
                    throw new Error('Provided selector is not an HTML object nor String')
                    return null
                }
            } else {
                element = elementOrSelector
            }

            if (element.tagName.toLowerCase() === 'svg') {
                svg = element;
            } else {
                if (element.tagName.toLowerCase() === 'object') {
                    svg = element.contentDocument.documentElement; // line 1737
                } else {
                    if (element.tagName.toLowerCase() === 'embed') {
                        svg = element.getSVGDocument().documentElement;
                    } else {
                        if (element.tagName.toLowerCase() === 'img') {
                            throw new Error('Cannot script an SVG in an "img" element. Please use an "object" element or an in-line SVG.');
                        } else {
                            throw new Error('Cannot get SVG.');
                        }
                        return null
                    }
                }
            }

            return svg
        }
```

So I don't really know what's going on there. Any help would be appreciated.

Regards

**Comment by bumbu** [comment]
I suppose you initialize the library with wrong options.
Please provide a live example ([as mentioned here](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues)). When you'll do so I'll reopen this issue.

**Comment by Seiifer** [comment]
Ok, so I managed to make it work on Plunker, however, it works as expected only in the embedded view : http://embed.plnkr.co/0nufcYZpE3ZzGxKQmUkf/preview
This is working on Chrome with this url, but when you download the zip and run it locally, it works only on firefox...
Also, I need to click twice on the menu to change properly but this is another issue that I already opened on stackoverflow (http://stackoverflow.com/questions/29518756/losing-zoom-pan-when-changing-svg-source)

**Comment by Seiifer** [comment]
Now, since I added something to handle resizing : 
```javascript
window.onload = function() {
    document.getElementById("svgElement").style.width = window.screen.availWidth + "px";
    document.getElementById("svgElement").style.height = window.screen.availHeight + "px";
    window.panZoom = svgPanZoom('#svgElement', {
        zoomEnabled: true,
        controlIconsEnabled: true,
        fit: true,
        center: true,
        minZoom: 0.75,
        maxZoom: 50,
        zoomScaleSensitivity: 0.25,
        dblClickZoomEnabled: true
    });
};

window.onresize = function(){
    window.panZoom.resize();
    window.panZoom.fit();
    window.panZoom.center();

    var scope = angular.element(document.getElementById("svgElement")).scope();
    scope.$apply(function(){
        scope.bannerHeight = window.innerHeight * 0.2;
    })

};
```
 I have now in console (on Chrome) : 
```terminal
Uncaught TypeError: this.options.svg.createSVGMatrix is not a function
Uncaught TypeError: Cannot read property 'resize' of undefined
```

So it looks like my :  `window.panZoom = svgPanZoom(...);` failed.

**Comment by Seiifer** [comment]
I added a few logs in order to understand better what is going wrong.
I hope this might help : 

So first : 
![this](https://cloud.githubusercontent.com/assets/7030689/7348159/686920fa-ecef-11e4-9455-1aabdf58ec32.PNG)

Result in Firefox : 
![this-ff](https://cloud.githubusercontent.com/assets/7030689/7348164/7a915888-ecef-11e4-80e5-e401cedf5f0d.PNG)

Result in Chrome :
![this-chrome](https://cloud.githubusercontent.com/assets/7030689/7348170/875d7f2e-ecef-11e4-8f42-a2c8ff70ca24.PNG)

Then :
![options](https://cloud.githubusercontent.com/assets/7030689/7348177/9631bd08-ecef-11e4-96b0-cd026377aca1.PNG)

Result in Firefox : 
![options-ff](https://cloud.githubusercontent.com/assets/7030689/7348180/a0dfcefc-ecef-11e4-80eb-916e6b19650d.PNG)

Result in Chrome :
![options-chrome](https://cloud.githubusercontent.com/assets/7030689/7348186/b707d94a-ecef-11e4-9013-e233f8c9ef0c.PNG)

And finally :
![options-svg](https://cloud.githubusercontent.com/assets/7030689/7348192/c2b027f2-ecef-11e4-9240-a5cda102bc2c.PNG)

Result in Firefox :
![options-svg-ff](https://cloud.githubusercontent.com/assets/7030689/7348194/cab3e29a-ecef-11e4-92ed-8dada16bf310.PNG)

Result in Chrome :
![options-svg-chrome](https://cloud.githubusercontent.com/assets/7030689/7348200/d1a935aa-ecef-11e4-82f3-70f960128ef0.PNG)


And indeed, Chrome values look wrong.
From what I understand, `this.options.svg` is displayed as a SVG element in Firefox while it is showed as a html element in Chrome.

**Comment by bumbu** [comment]
Yes, it seems that selected element in Chrome is HMTL (root dom element). Either you did the selection wrong, or there is something about selection timing vs SVG creation timing.

**Comment by Seiifer** [comment]
This might be related : when I try to run the zip i downloaded from the plunker I get this error in Chrome console : 
```terminal
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLObjectElement': Blocked a frame with origin "null" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "data". Protocols must match.
module.exports.getSvg @ svg-pan-zoom.js:1738
svgPanZoom @ svg-pan-zoom.js:1271
window.onload @ viewerController.js:81

**Comment by Seiifer** [comment]
For some mystic reason, it worked one time on Chrome. Then I refreshed my page and it didn't work anymore. So the suggestion about timing that you made might be correct.
The logs I had on Chrome the one time it worked : 
```
elementOrSelector : #svgElement
element : [object HTMLObjectElement]
element.contentDocument : [object XMLDocument]
```
The only difference with Firefox is that we have an XMLDocument instead of a SVGDocument in the object.

Now I'm back with the `element.contentDocument : [object HTMLDocument]`

Also, to check if the SVG element is wrong from the beginning I tried in the very first called function : 
```javascript
    var SvgPanZoom = function(svg, options) {
        console.log("SVG : " + svg);
        this.init(svg, options)
    }
```

which gives :
in Chrome : `SVG : [object HTMLHtmlElement]`
in Firefox : `SVG : [object SVGSVGElement]`

So yeah I have HTML instead of SVG from the beginning. I don't know if it is related to the same-origin policy that I mentioned in the last comment I edited.

**Comment by bumbu** [comment]
Maybe it is because your SVG (object) is invalid in Chrome because its data attribute points to nowhere.
I do remember that in Angular there is a special way to handle dynamic images by using `ng-src` instead of `src` because you may have some problems by setting an invalid source. It may be the same case here.

**Comment by Seiifer** [comment]
It looks like you're right.
In this code : 
```html
<object id="svgElement" type="image/svg+xml" data="../SVG/{{currentLanguage}}/{{currentCartography}}.svg">
    It seems your browser doesn't support SVG.
</object>
```
You mean that since angular scope variables such as `currentLanguage` and `currentCartography` aren't yet initialized after the DOM is loaded, Chrome refuses to 'accept' the `<object>` ?

Indeed, if I set a static path into my data attribute, it works in Chrome.

Could it also be the reason why I need to click twice to change a SVG ?
And is there any way you know of to force angular scope variables to be loaded before the html page ?

**Comment by bumbu** [comment]
I don't know how to force angular scope variables to be loaded before the html page. I do believe that it is not possible. 

But one solution would be to not rely on angular variables to change the object and do it manually whenever you need it. An example is available [here](https://github.com/ariutta/svg-pan-zoom/blob/master/demo/dynamic-load.html).

**Comment by Seiifer** [comment]
Well, managed to fix it in Chrome with 
```html
<!-- SVG : main content -->
<object ng-show="currentCartography" id="svgElement" type="image/svg+xml" data="../SVG/{{currentLanguage}}/{{currentCartography}}.svg">
    It seems your browser doesn't fully support SVG.
</object>
```
However, this fix doesn't work on IE. But this is not a priority for me now.

**Comment by philipLutz** [comment]
I am having this same problem using Chrome to use this svgPanZoom on an SVG within an <object>.  It works on Firefox, and the only other difference is that I am not using Angular.  I don't understand what your fix was for Chrome.
