### ISSUE TITLE
.fit() and .center() not working for certain SVGs

### ISSUE THREAD

**Issue by oller** [ariutta/svg-pan-zoom#111]
First off, fantastic library! :+1: 

I'm having trouble getting `.fit()` and `.center()` to work for some svg files I'm working on.  These worked when the viewBox was declared, but this causes issues in IE as discussed in Issue https://github.com/ariutta/svg-pan-zoom/issues/21

As a result, I've ripped out the viewBox attribute in order to fix this, but that causes this problem with these functions.  I'm not sure if this is related some existing transform's in the svgs.

I've put a fiddle where you can see this problem.

http://jsfiddle.net/167usffr/96/

If you inspect the DOM, you'll see the `<svg>` and `<g class="svg-pan-zoom_viewport">` are significantly misaligned.

This doesn't occur with the tiger svg, so I'm aware the problem must originate from something in the SVG itself, I'm just not sure which aspect is causing the problem and how I could remedy this, via either some additional initialisation code, or amending the SVG file.

Thanks!

**Comment by bumbu** [comment]
From what I see the viewBox is not computed right if nested `g` elements have transform attributes. 
I'm not sure if it is possible to be solved but we have to look into [`getBBox`](https://github.com/ariutta/svg-pan-zoom/blob/master/src/shadow-viewport.js#L65).

**Comment by oller** [comment]
Hi @bumbu, I agree that looks like where the problem most likely lies.

Out of interest, if I strip all `transform=""` attributes out of the svg, it still fails to `.fit()` and `.center()` correctly, if not a little nearer.

http://jsfiddle.net/167usffr/98/

**Comment by bumbu** [comment]
Yes, it looks strange. I see an error of ~9px for a 400px width.
It may be because of rounding error, of because of something else. It needs a research.

Maybe the first bug you showed is also based on that error. And solving this one will solve both of them.

**Comment by oller** [comment]
I've made some progress debugging this...

http://jsfiddle.net/167usffr/99/

Calling the  `.updateBBox()` function prior to calling `.fit()` and `.center()` gets us closer to where we want to be.  Contrast the behaviour when the custom button is hit compared to the `reset` button in the map controls.  It gets the correct zoom scale, it's just seems the `.center()` method is still failing to act upon this updated zoom of the viewport.

From the console logs, you can see the `updateBBox` updates and corects the `realZoom` value

**Comment by oller** [comment]
I see `updateBBox` `0`'s the x and y when `recacheViewBox()` is called. (https://github.com/ariutta/svg-pan-zoom/blob/master/dist/svg-pan-zoom.js#L231-L232).

Whereas `cacheViewBox` doesn't do this (when no svgViewBox is defined).  Should this not be consistent?  This seems to be part of the problem for me if the following lines https://github.com/ariutta/svg-pan-zoom/blob/master/dist/svg-pan-zoom.js#L215-L216 set `x` and `y` to 0 too.

Also - I may be going off on a tangent, but your simple tiger example inline demo has `fit` and `center` set to `true` but on chrome canary, this initialises like the screenshot below for me.
http://ariutta.github.io/svg-pan-zoom/demo/inline.html  

![image](https://cloud.githubusercontent.com/assets/1219831/7912282/fafa6b84-085d-11e5-8ffb-8580f739e7db.png)

Any thoughts?  Thanks

**Comment by vladdu** [comment]
Regarding the tiger, it has the origin in the middle instead of the top left corner. The fit and center functionality assume that the origin is in the corner. 

I'm not sure if it's this that also causes 'fit' to scale the image at 55% - it should fill the viewport, right?

**Comment by bumbu** [comment]
I remember that tiger in `inline` example was in top-left corner for some good time. And I remember that I knew why. Now it seems to be strange. It may be because of viewBox and/or matrix transform.

But I have to check that out in order to be sure if there is a bug or it is normal behavior caused by some settings.

**Comment by oller** [comment]
Sorry, I didn't mean to derail the initial issue.

Do you guys have any thoughts on the previous comment https://github.com/ariutta/svg-pan-zoom/issues/111#issuecomment-107416875  .  Relating to `cacheViewBox` and `recacheViewBox` not consistently `0`'ing the `x` and `y` co-ords? 

That gets this issue half fixed, in that the scale is now correct, it's just the `center()` action still fails, I suspect it's acting on old data.

**Comment by bumbu** [comment]
Currently I'm really busy but as soon as I get some free time in my schedule I'll look into both issues.
Or if anyone else can figure out what's the problem and can create a Pull Request with a solution - it would be great.

**Comment by bumbu** [comment]
@oller now I remember why inline demo looks like this: because viewport attribute had `transform` attribute. In [documentation](https://github.com/ariutta/svg-pan-zoom#using-a-custom-viewport) it is mentioned that viewport should have no `transform` attribute.

**Comment by bumbu** [comment]
@oller - I think I found what the bug was. I pushed the change into *dev* branch. Can you please test it?
From what I tested - it was working fine now.

**Comment by oller** [comment]
@bumbu great stuff!  I can confirm this fixes the issue for me.  Thanks again, great library!
