### ISSUE TITLE
Localization of RESET text in zoom control

### ISSUE THREAD

**Issue by cervengoc** [ariutta/svg-pan-zoom#112]
Is there any way to localize the RESET text in the zoom control? I've briefly checked the code but couldn't find this text anywhere. 

Thanks

**Comment by ariutta** [comment]
Currently there isn't any i18n support, but that's a good idea. For now,
you could replace the reset element via the DOM.

**Comment by bumbu** [comment]
Also you can use your [custom controls](http://ariutta.github.io/svg-pan-zoom/demo/custom-controls.html).
