### ISSUE TITLE
SVG rendering upside down.

### ISSUE THREAD

**Issue by LFJake** [ariutta/svg-pan-zoom#113]
When loading certain SVG's they render upside down and backwards, as well as not being able to zoom in and out of the image. I have attached an image of the bug that is occuring as well as an image of the expected result. Github issues will not let me attach an SVG file to this issue so if you would like the file I would be more than happy to email it to you.
![correctrendering](https://cloud.githubusercontent.com/assets/7998352/7614217/a624bfd4-f952-11e4-89a3-685c4a4e6e78.png)
![upsidedown](https://cloud.githubusercontent.com/assets/7998352/7614219/a7af15f2-f952-11e4-8e11-d57f8adee1ad.png)

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#bugs-and-issues
