### ISSUE TITLE
SVG rendering upside down.

### ISSUE THREAD

**Issue by LFJake** [ariutta/svg-pan-zoom#115]
I am having issues with some SVG's being rendered upside down.  You can view the problem at http://jsfiddle.net/1j68pfyn/4/, the expected result is for the numbers and image to be rotated 180 degrees so that they are upright. I am using svg-pan-zoom version 3.1.3 and the bug appears in chrome, IE and firefox in both windows and linux.

**Comment by bumbu** [comment]
It seems to be from the library. Maybe it is because of small numbers (SVG's sizes are small and use viewBox to show only visible part).

Needs research.

**Comment by LFJake** [comment]
Ya it could be because of the small numbers but I have other SVG's of the same scale and they render fine.

**Comment by bumbu** [comment]
@LFJake - it seems that I fixed this issue by fixing another one (#111). Can you please test it against the code from [dev](https://github.com/ariutta/svg-pan-zoom/tree/dev) branch?

**Comment by LFJake** [comment]
@bumbu - That fix works! Thanks for looking into this bug and getting a change out quickly. One other thing I noticed when testing is it now seems that zooming in and out with the mouse-wheel is reversed from the version in master. Do you want me to submit a new bug for this?

**Comment by bumbu** [comment]
@LFJake is zooming reversed only on your SVGs (that were reversed) or on all SVGs (ex. demo/inline.html)?

It may be because of https://github.com/ariutta/svg-pan-zoom/commit/069d7020797ab7f9286f2efe11f756cd2d9b87e8
Can you please tell me your browser, its version and OS?

**Comment by bumbu** [comment]
Yes, I had the same thing. It was introduced in https://github.com/ariutta/svg-pan-zoom/commit/069d7020797ab7f9286f2efe11f756cd2d9b87e8 and I didn't observed that. Thanks for that!

I fixed it in https://github.com/ariutta/svg-pan-zoom/commit/0fb6b8a5eedab07f77a91b622d1079a79aeaccb0. Let me know if it is ok now.

**Comment by LFJake** [comment]
Everything looks good now, thanks for the support this library is a huge help for my project.
