### ISSUE TITLE
Zoom issue with pan limits

### ISSUE THREAD

**Issue by GruberMischa** [ariutta/svg-pan-zoom#116]
First of all: Great work!

If I try to zoom in with defined pan limits, the viewport moves near the center of the svg.
This happens only if I zoom at the bottom right corner of the square. Zoom on the top left corner will not pan the svg.
The bigger the limits, the bigger the pan distance.

To see the issue:
jsFiddle: http://jsfiddle.net/m8o59j1o/
zoom out as much as possible and move the square to the upper left corner.
Then double click on the bottom right corner of the square. The mouse pointer moved.

Library: Version 3.1.3
Browser: Chrome 42.0
OS: Windows 8.1

**Comment by bumbu** [comment]
I tried to reproduce this but it works fine for me on Chrome on OSX

**Comment by ariutta** [comment]
I'm not sure I understand what you mean by "The mouse pointer moved." Are you saying that the limits appear to change when you zoom in, ie., if the box is as far to the top-left corner as possible when zoomed out, then you zoom in, you can move the box further up and to the left?

**Comment by bumbu** [comment]
I'm closing it as I again wasn't able to reproduce the bug (or understand it). 
If you'll provide more details then I can reopen it.
