### ISSUE TITLE
Is there a way panzoom can work as background image.

### ISSUE THREAD

**Issue by kennethjfalbous** [ariutta/svg-pan-zoom#118]
Like the way I want to to work it,  image should be in background the height should be as long as the page.

right now the if we want to panzoom the image we need to put the mouse on the image and then scroll it. What I require is that if there is a way that with the main scroll of the website image starts zooming out irrespective of the height and in the background.

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help
