### ISSUE TITLE
script70 permission denied ie 11 

### ISSUE THREAD

**Issue by deeypak** [ariutta/svg-pan-zoom#119]
Hi,
I am loading the svg files dynamically,and zooming,panning functionality are activated on loading the svg image,some times the zooming ,panning functionalities does not work on loading the svg image.

when dynamica svg loaded ,on click of zoom or pan gives me "script70 permission denied in ie 11"
 embed.addEventListener('load', function() {	    	
    	if(enableHotSpot){
    		highlight2dNode('_'+lastBomItemNumber);
    	}
		addDynamicSvgUrl();					
		registerEvents();		
		 svgPanZoom(embed, {
				zoomEnabled: true,
				controlIconsEnabled: false
			  });			 		
	});

above method loads the dynamic svg file ,and registerEvents() function is used for enabling zoom,pan functionality sometimes while loading multiple svg files ,zooming and panning does not work and give 
"script70 permission denied in ie 11" in the console,
This problem occurs only in IE11.

**Comment by bumbu** [comment]
The library works only with preloaded SVG elements. An example of loading SVGs dynamically is provided [here](https://github.com/ariutta/svg-pan-zoom/blob/master/demo/dynamic-load.html).

If it's not the case then first read how to report bugs/issues here: https://github.com/ariutta/svg-pan-zoom#bugs-and-issues
