### ISSUE TITLE
alternative zoom/pan controls

### ISSUE THREAD

**Issue by vladdu** [ariutta/svg-pan-zoom#120]
I would like to implement zoom/pan controls in form of a miniature image of the whole svg, with an outline of the current viewport. I think you know what I mean. 

Does anyone have a suggestion about how to do that? Is there any library that can help me here? 

Would it be interesting to include that feature in svg-pan-zoom?

**Comment by bumbu** [comment]
It seems to be a duplicate for #110 
If it is not a duplicate then I'll reopen this issue, otherwise check the answer for that issue.
