### ISSUE TITLE
Scroll-zoom too sensitive

### ISSUE THREAD

**Issue by AlexanderPico** [ariutta/svg-pan-zoom#122]
Given the scroll sensitivity I have set in my OS preferences, it seems like the scroll-driven zoom is way too sensitive in this lib. I rarely can achieve the zoom level I want with scrolling and most often accidentally zoom way in or way out to a ridiculous degree without intending to. Is it possible to dampen the effect? 

Mac OSX 10.10.2, Chrome 43, apple "magic mouse"

**Comment by bumbu** [comment]
Can you please provide an example?
I have the same setup as yours (including the mouse) and it works fine for me on demos.

**Comment by AlexanderPico** [comment]
Any pathway at WikiPathways, e.g., http://wikipathways.org/index.php/Pathway:WP585

The usable zoom range is fairly narrow, so to have it zoom way in and way out with a minor movement makes it difficult to use.

**Comment by AlexanderPico** [comment]
And to be clear, pinch-zoom and click-zoom work well, it's just scroll-zoom on touch pads and the touch mouse that I find too sensitive.

As far as I can tell, we are using the latest 3.1.3 release in our current builds of kaavio/pvjs.

**Comment by AlexanderPico** [comment]
Here's another way to describe the issue. We have set the min and max zoom at WikiPathways (which works great), but when I try to scroll-zoom using a track pad or magic mouse, I zoom through the entire range moving ~1 finger-tips width (my track pad is ~12 widths long). So, mouse ~92% of my trackpads scroll length is not being utilized, i.e., hits the min/max limits, and just ~8% of the trackpad is used to control the zoomable range of the pathway.

Again, my trackpad scrolling settings in my OS are not that sensitive for other operations. In order to scroll the full page length of that same pathway example, I have to do almost 2 full swipes across my trackpad.

**Comment by bumbu** [comment]
@AlexanderPico I implemented another mouse wheel normalization. Now it seems to work smoother.
Can you please check it [here](http://jsfiddle.net/bumbu/tahLn00q/)? 
Before we can merge it into master we need to test as much as possible this change.

**Comment by AlexanderPico** [comment]
Perfect! That's exactly the zoom response I'd expect, given my OS settings. I tested zooming a bunch and moving the center of zoom. All looks good to me. Not sure what else to "test"...

**Comment by bumbu** [comment]
You could test in other browsers/on other machines if you have access to any. 
I think we'll merge it into master and will release as version 3.2.

**Comment by AlexanderPico** [comment]
FF on Mac: doesn't work at all. No scroll-zoom via scroll mouse or trackpad. The zoom doesn't change with scroll action.

**Comment by AlexanderPico** [comment]
Also on FF on Mac: The current release works just fine. Scrolling changes the zoom. In fact, the rate of change is really nice in FF, in contrast to chrome, in this current release...

**Comment by bumbu** [comment]
I updated scroll sensitivity normalisation. A demo is [here](http://jsfiddle.net/bumbu/tahLn00q/1/). @AlexanderPico can you please check it once again?

This time I tested it in Chrome, Firefox, Opera, IE in both OSX and Windows with both Magic Mouse and usual mouse. It seems to work fine now.

**Comment by AlexanderPico** [comment]
Nice. It was still just a bit too sensitive, imho, so I submitted a pull request knocking zoomScaleSensitivity down from 0.2 to 0.1. I think this is a good compromise: a bit more than expected in Chrome and a bit less than expected in FF, but all useable. 

Thanks!
