### ISSUE TITLE
Zoom HTML Content

### ISSUE THREAD

**Issue by YipYipX4** [ariutta/svg-pan-zoom#125]
Is there any chance that this control could be used to zoom regular (non-SVG) HTML content (using the css zoom property and other tricks for clipping & panning)?  

I did quickly try this with the starter jsFiddle and it didn't work, so I assume that the SVG zooming is done with something SVG specific.

If there's no chance, then please go ahead and close this issue.

Thanks!

**Comment by YipYipX4** [comment]
Here's the jsFiddle: http://jsfiddle.net/167usffr/110/

**Comment by bumbu** [comment]
You're right. Zooming is done using SVG specific attribute - `transform`. So it is not possible to pan/zoom non-SVG content.
