### ISSUE TITLE
center not working on Firefox

### ISSUE THREAD

**Issue by charliebevis** [ariutta/svg-pan-zoom#127]
On the latest version of Firefox, the [jsfiddle linked from this library's homepage](http://jsfiddle.net/bumbu/167usffr/) does not center its content. The controls on the element are also out of position. Poking at it, it's not clear to me why this isn't working.

**Comment by bumbu** [comment]
Please [mention your browser name, version and operating system](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues)

**Comment by charliebevis** [comment]
I was running an [extended support release](https://www.mozilla.org/en-US/firefox/organizations/) of firefox (31.7.0) on Windows 7. I've updated to 38 and things look excellent. Thanks.

**Comment by bumbu** [comment]
It may not work on older browser versions. Especially with Firefox there were more problems in version 33 and 34 (or something close to these versions).
