### ISSUE TITLE
Adobe Illustrator SVG Showing up small

### ISSUE THREAD

**Issue by juscook10** [ariutta/svg-pan-zoom#128]
I am trying to use an SVG file that I created in Adobe Illustrator that was original created in AutoCAD.  I can't get it to fill my container.  Any ideas?

http://jsfiddle.net/juscook10/ga6ezkab/

**Comment by bumbu** [comment]
From what I see it does fill the SVG.
On the other hand your SVG does not fill `#container` div but it is another thing that can be solved by adding some width and height using CSS (see the examples).

If this still doesn't help you then please provide all the information from [this](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues) section. Also please attach some screenshots that will explain how it looks for you and how it should look in fact.
