### ISSUE TITLE
Can i disable Pan while elements of the SVG are being dragged

### ISSUE THREAD

**Issue by rafialikhan** [ariutta/svg-pan-zoom#129]
I have an SVG which has some elements which are draggable (using snapsvg to generate the SVG). Unfortunately, when panEnabled: true, the element is dragged and the svg is panned at the same time, which is not a desirable. Anyway to turn off PAN only when a draggable element is dragged?

**Comment by bumbu** [comment]
It should be possible to do so. You'll have to disable svg-pan-zoom pan functionality `disablePan()` on drag start (or keydown event) and reenable it `enablePan()` on drag end (or keyup event).
