### ISSUE TITLE
Allowing Touch Scrolling When Pan is Disabled?

### ISSUE THREAD

**Issue by wheen-** [ariutta/svg-pan-zoom#131]
I'm trying to make it so that users on touch screens can still scroll the page by initiating the drag with their finger on the svg. So far, I've disabled pan until the user tries zooming, but I'm unsure of where to go from there. I feel like I have to remove touch listeners (And then add them in when I re-enable panning), but I'm unsure of how I would go about doing that.

Thanks in advance for any help that could be provided.

**Comment by bumbu** [comment]
You may take a look at [Custom events: Touch events support: pan, double tap, pinch](https://github.com/ariutta/svg-pan-zoom#demos) demo. There you have an example how to disable specific event handlers and replace them with your own.

Or you can use `preventMouseEventsDefault: false` (this will disable `preventDefault` for both mouse and touch events). But if you initialize `svgPanZoom` with this configuration then there will be no option to enable it back (you can add a pull request for such an option).
