### ISSUE TITLE
How to calculate the X Y poistion of an element with respect to HTML body after PAN & Zoom

### ISSUE THREAD

**Issue by rafialikhan** [ariutta/svg-pan-zoom#132]
Hi, I am unable to get the absolute X Y co-ordinates after PAN and ZOOM. Since the reference is with respect to the SVG container, unable to calculate with respect to page. As i require to HTML show a action box next to an SVG element. ClientX and ClientY or mouse event X and Y are not updated after panned / zoomed.

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help
