### ISSUE TITLE
Dynamic load SVG flashing (twitch)

### ISSUE THREAD

**Issue by altukhov-a** [ariutta/svg-pan-zoom#133]
Hi, I use example with dynamic load SVG in my project. I see the problem, when new SVG replaces the current visible SVG, it sometimes twitches, especially if it is larger than 1 Mb. How can I solve this problem?

**Comment by altukhov-a** [comment]
It seems I solve my problem by add ```this.updateCTM()``` in the end of this method
```
ShadowViewport.prototype.init = function(viewport, options) {
  // DOM Elements
  this.viewport = viewport
  this.options = options

  // State cache
  this.originalState = {zoom: 1, x: 0, y: 0}
  this.activeState = {zoom: 1, x: 0, y: 0}

  this.updateCTMCached = Utils.proxy(this.updateCTM, this)

  // Create a custom requestAnimationFrame taking in account refreshRate
  this.requestAnimationFrame = Utils.createRequestAnimationFrame(this.options.refreshRate)

  // ViewBox
  this.viewBox = {x: 0, y: 0, width: 0, height: 0}
  this.cacheViewBox()

  // Process CTM
  this.processCTM()
  this.updateCTM()
}

```

**Comment by bumbu** [comment]
Can you please show an example? It will help me to check if this improvement can be added to the library.

**Comment by altukhov-a** [comment]
Hi, only example that I can give https://github.com/altukhov-a/svg-pan-zoom/tree/master/example
I n the end of function ```ShadowViewport.prototype.init``` I add ```alert('')``` to interrupt execution to be seen, that after init SVG image show in original size, and only then resized

**Comment by bumbu** [comment]
Thank you. I'll check if it is ok to use your solution or if there are any other things that should be taken into account.

**Comment by bumbu** [comment]
Your solution was right. Thanks a lot!
