### ISSUE TITLE
why don't I get the correct coord

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#135]
My require:  I need get correct coord when I double click the svg 's location by mouse.

MY suggestion: 
1 the Author need add  checkLimits,(forbid not viewport's coord)
2 I can get the correct coord although I zoomin or zoomout at one fixed point of svg.But now you can know the coord will be changed with viewbox's data. Because I need input fixed data ,I can't hope the fixed data's coord will be changed randomly. 

MY function:
/**
 * Handle double click event
 * See handleMouseDown() for alternate detection method
 *
 * @param {Event} evt
 */
SvgPanZoom.prototype.handleDblClick = function(evt) {
  var point = getViewBoxCoordinatesFromEvent(this.svg, evt);
   document.getElementById('mouselnginput').value=point.x+","+point.y;   

My email:liyihong123456@163.com

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#bugs-and-issues
