### ISSUE TITLE
How to setCenter(x ,y)?

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#136]
I can't find the function setCenter(x ,y) in jquery plugin.
I need find the fixed coordinate position when I zoom and pan svg.
My data is from DB and so I need draw them in svg when I zoom and pan.
Please notice x,y is initial coordinate and not screen coordinate

Please refer to (It provides the setCenter)
https://github.com/DanielHoffmann/jquery-svg-pan-zoom/

**Comment by liyihongcug** [comment]
Thanks , I get the answer below.
panZoom.pan
({  
x: -(755*realZoom)+(panZoom.getSizes().width/2),
y: -(240*realZoom)+(panZoom.getSizes().height/2)
}); 

But I now have new request(New question),  and it is below:
when I click the svg's point in viewport, how to get  its real coordinate.
Please notice it . 
For example when I cilck the rect( id=myrect) whose real coordinate  is (50,50),How  can I get it?  (svg-pan-zoom only get  var point = SvgUtils.getEventPoint(evt, this.svg).matrixTransform(this.svg.getScreenCTM().inverse())  --------------it only is screen point)

example  Codes are below:
<div id="mobile-div" style="width: 602px; height: 420px; border:1px solid black; ">
      <svg id="mobile-svg" xmlns="http://www.w3.org/2000/svg" width=600 height=400 style="display: inline; width: inherit; min-width: inherit; max-width: inherit; height: inherit; min-height: inherit; max-height: inherit;" version="1.1" preserveAspectRatio="xMinYMin meet" style="border:1px solid #cd0000;">>
        <defs>
          <linearGradient id="linear-gradient" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:rgb(56,121,217);stop-opacity:1" />
            <stop offset="100%" style="stop-color:rgb(138,192,7);stop-opacity:1" />
          </linearGradient>
        </defs>
        <g fill="none">
          <g stroke="#000" fill="#FFF">
            <rect x="5" y="5" width="240" height="240" fill="url(#linear-gradient)"/>
            <path d="M 5 5  L 245 245 Z"/>
			 <rect id=myrect x="50" y="50" width="5" height="5" fill="url(#linear-gradient)"/>---------I add it
          </g>
        </g>
      </svg>
    </div>

**Comment by liyihongcug** [comment]
example Codes are below:<rect id=myrect x="50" y="50" width="5" height="5" fill="url(#linear-gradient)"

**Comment by bumbu** [comment]
[It is not a bug or issue](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues).

As a hint you have to use `getSizes`, `getPan` and `getZoom` methods. Having all these values and the click event values - you can compute its relative and absolute coordinates.

**Comment by ekonoval** [comment]
I have encountered this topic by searching how to get real svg coordinates on click. I've found only a hint here so I decided to share my solution.

function cursorPoint(evt) {
    var svg = document.getElementById('mobile-svg');
    var pt = svg.createSVGPoint();
    pt.x = evt.clientX;
    pt.y = evt.clientY;
    return pt.matrixTransform(svg.getScreenCTM().inverse());
}

$("#mobile-svg").click(function(evt){
    var pan = panZoom.getPan();
    var zoom = panZoom.getZoom();

    var x, y, pt;
    pt = cursorPoint(evt);

    x = pt.x;
    y = pt.y;

    if (zoom == 1) {
        x -= pan.x;
        y -= pan.y;
    } else {
        x = (x - pan.x) / zoom;
        y = (y - pan.y)/zoom;
    }
});
