### ISSUE TITLE
How to add my customed event in order to obtain current viewport's real scope

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#138]
My requirement:
I can get current viewport svg's real scope when I zoom ,pan and wheel svg.Thus I can calculate its current place area rate/original svg full map  in eagle window.

My research development : I read codes and find these functions below:
SvgPanZoom.prototype.zoomAtPoint =
vgPanZoom.prototype.pan = 
vgPanZoom.prototype.panBy=
wheel (sorry ,wheel is comflex and it should use addeventlistener)
Now I choose the easy function zoomAtPoint .========SvgPanZoom.prototype.zoomAtPoint = function(zoomScale, point, zoomAbsolute) {
  var originalState = this.viewport.getOriginalState()
........................
  alert(111)   (stand for my handle event)  ----------------------------  I find it always start early.whether I need create my callback function  or use my Asynchronous function in your js plugin but I don't think it is good.

Thanks for help.

**Comment by liyihongcug** [comment]
I have finished SvgPanZoom.prototype.zoomAtPoint function  but I can't pass pan/panBy.
why pan/PanBy can't support  alert(1)???

Codes are below:
SvgPanZoom.prototype.pan/ panBy = function(point) {
  var viewportCTM = this.viewport.getCTM();
  viewportCTM.e = point.x;
  viewportCTM.f = point.y;
  this.viewport.setCTM(viewportCTM);
  alert(1);                            ---------------------------------  It doestn't response so that I can't add my event

**Comment by liyihongcug** [comment]
I solved it  .  mousewheel is in handlemouseup. The answer is Asynchronous function.
Do u agree it?

**Comment by bumbu** [comment]
Sorry, but I do not understand your question. 
And for adding code examples you should better use [github markdown] so that the code stays readable.

I'm closing this as you said you solved it.
