### ISSUE TITLE
Get the layer which will be panned and zoomed at the bottom of the layer Z order

### ISSUE THREAD

**Issue by tranxen79** [ariutta/svg-pan-zoom#139]
Hi, 

I tried everything I could but I was unable to set this JS library to work with my bottom layer. I need to pan and zoom this one but I also need to have other layers over. The top layers have graphics which must be always displayed and which shall not move. Is there a way to so ?

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#using-a-custom-viewport
Create a group element with `svg-pan-zoom_viewport` class. Or specify your own selector in options.

**Comment by tranxen79** [comment]
Thanks for the answer. 

I already tried because when I said layer it meant G element? If I do so the top layers disappear as if they become bottom layers. One solution was to nest my top layers into a svg but the zoom pan performance drastically dropped !

**Comment by bumbu** [comment]
You can have your zoom/pan-able layer on top and bottom. See [this example](http://ariutta.github.io/svg-pan-zoom/demo/layers.html).
