### ISSUE TITLE
How to forbid the pan/zoom

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#143]
I need calculate the distance in svg. But it supports pan/zoom by default so that the web is always swifting. The user experience is not good.
Now I need svg-pan-zoom can add 2 functions  :  setforbidpan  /  setforbidzoom
So I can open the forbid function when I calculate the distance.

for examples:
window.panZoom = svgPanZoom('#mobile-svg', {
          zoomEnabled: true
        , controlIconsEnabled: true
        , fit: 1
        , center: 1
        , customEventsHandler: eventsHandler
        });
         I can use  panZoom.setforbidpan(0)-------------> forbid 
          (at the same time ,I hope panZoom.setforbidpan(0)  stands for shutting up the function)

**Comment by bumbu** [comment]
From [How to use section](https://github.com/ariutta/svg-pan-zoom#how-to-use):

`beforeZoom` will be called with 2 float attributes: oldZoom and newZoom.
If `beforeZoom` will return `false` then zooming will be halted.

`beforePan` will be called with 2 attributes:
* `oldPan`
* `newPan`

Each of this objects has two attributes (x and y) representing current pan (on X and Y axes).

If `beforePan` will return `false` or an object `{x: true, y: true}` then panning will be halted.
If you want to prevent panning only on one axis then return a object of type `{x: true, y: false}`.
You can alter panning on X and Y axes by providing alternative values through return `{x: 10, y: 20}`.

> *Caution!* If you alter panning by returning custom values `{x: 10, y: 20}` it will update only current pan step. If panning is done by mouse/touch you have to take in account that next pan step (after the one that you altered) will be performed with values that do not consider altered values (as they even did not existed).
