### ISSUE TITLE
Is there any way to filter the view output by size of the svg element?

### ISSUE THREAD

**Issue by liveman1** [ariutta/svg-pan-zoom#144]
Hi, it would be great if one could implement an adaptive zooming in order to load smaller svg elements with an increasing zoom level. This way high-dense svg images would load with less content & performance could be increased.

**Comment by bumbu** [comment]
There is no such functionality and there are no plans to do something like this because it is too specific. 
But it should be quite straight-forward to implement that using `onPan` method. At each `onPan` call you can check current zoom level and replace the elements you want more/less detailed.
