### ISSUE TITLE
Plugin is very slow and sometimes fails to work with large SVG documents

### ISSUE THREAD

**Issue by haykpetros** [ariutta/svg-pan-zoom#145]
It seems that plugin works extremely slow, or most of the time causes browser to crash or ask user to stop a very slow running script, when SVG documents is bigger than 6MB or so. Hard to say what can cause this, as it won't slow down gradually, but instead will work just fine with 6MB files, but then suddenly stop with a little bit larger ones.

Here is the link for sample SVG that fails: [ Large SVG Document.svg](https://gist.github.com/haykpetros/ffa6c5de616849cd1047)

**Comment by bumbu** [comment]
The link you provided doesn't work. [This is a correct one](https://gist.github.com/haykpetros/ffa6c5de616849cd1047).

Did you try using the same file but without this library? Most probably this is not the library issue but a browser limitation.

**Comment by haykpetros** [comment]
Yes I did and it loads just fine into all the browsers. More it works if used with [jquery.panzoom] (https://github.com/timmywil/jquery.panzoom) plugin as well.

**Comment by bumbu** [comment]
Same as #146
