### ISSUE TITLE
Prevent a click event on pan

### ISSUE THREAD

**Issue by jonnymaceachern** [ariutta/svg-pan-zoom#148]
I'm binding click events to polygons that display a tooltip. If the `mouseup` target is a polygon, the tooltip is shown. This becomes an issue when the user is panning because it will inadvertantly trigger the tooltip due to the `mouseup` being fired at the end of the pan. Is there a method I can call to check if a pan is active?

Edit:

I ended up finding a solution and figured I'd post it in case anyone else runs into this issue. Here's the snippet from [stackoverflow](http://stackoverflow.com/a/6042235/1822096) that I used to check for pans:

	// Check if the mouse is dragging

	var element = document.getElementById('canvas');
	var flag = 0;

	element.addEventListener("mousedown", function() {
		flag = 0;
	}, false);

	element.addEventListener("mousemove", function() {
		flag = 1;
	}, false);

	element.addEventListener("mouseup", function() {
		if (flag === 0) {
			console.log( "Click" )
		} else if (flag === 1) {
			console.log( "Drag" );
		}
	}, false);

**Comment by twjeric** [comment]
I encountered the same problem. I solved it by using the this.state in svg-pan-zoom.js with a trick. The main idea is alike.

**Comment by matheuscaldasrj** [comment]
Thanks from 2019 @jonnymaceachern
