### ISSUE TITLE
How to forbidden pan and zoom after I use window.panZoom = svgPanZoom('#limit-svg' for some time

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#149]
My application:
I need move one shape but svgPanZoom alway move with the shape. My targe is to only drag the shap of svg and don't move svg. In default  svgPanZoom  supports all shape behaviour : zoom and pan.

My design : I add one input button (click function:  when I click the button , It can forbidden the window.panZoom = svgPanZoom . And I re-click the button ,It can reopen the window.panZoom = svgPanZoom old function)

My wrong test:window.panZoom = svgPanZoom('#limit-svg', {
          zoomEnabled: false
        , controlIconsEnabled: false
        ,panEnabled: false
        });*       panZoom=Null  . They are wrong.
You can give me the way how to solve it?

**Comment by liyihongcug** [comment]
The answer is   panZoom.disablePan();
       panZoom.disableZoom();

Thanks.  I think I can makeup other new function. This JS is strong

**Comment by shyammbusa** [comment]
Hi Bumbu, If I need to Override the Drag from mouse to Button click in SVG PAN Zoom. How will I do that. That is I have 4 buttons like forward, backward , left and right. On clicking the same my SVG should move or drag forward ,backward ,left , right. Same time Mouse drag will as default drag and zoom present in SVG pan zoom js

**Comment by bumbu** [comment]
Hey @shyammbusa 

If I understand your question correctly then you want to add custom controls (there's a demo) and use `pan` and `panBy` methods that the library exposes. 

But for the future please use [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help) for questions like this of for more details.
