### ISSUE TITLE
How to zoom in/out only one shape element?(please notice ,not all svg layer)

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#150]
The plugin is good at zoom in/out in the whole svg file layer.
Now I need only zoom in/out one polygon shape element  onf the whole layer?
I have finished zoom in/out  the cirle ,rect ,polyline but I have no way how to deal with the complex polygon (not regular).
You know the polygon doesn't like rect. So I hope the plugin can provide zoom in/out only single shape element (rect circle polygon and so on).
Or you can provide some advide   to deal with this situation?

**Comment by bumbu** [comment]
Please, next time place [such questions on StackOverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help).

You can zoom one group element. You can place in it any elements you want. [Documentation](https://github.com/ariutta/svg-pan-zoom#using-a-custom-viewport). [Demo](http://ariutta.github.io/svg-pan-zoom/demo/layers.html).
