### ISSUE TITLE
Clip at edges?

### ISSUE THREAD

**Issue by mwojtul** [ariutta/svg-pan-zoom#157]
Is there a way to clip the SVG at the edges to basically prevent scrolling it beyond view?

[#37](https://github.com/ariutta/svg-pan-zoom/issues/37) deals with this, but I couldn't quite put it all together.

```
beforePan(oldpan, newpan) {
return { x: Math.max(newpan.x, 0), y: Math.max(newpan.y, 0) };
}
```

Comes close and limits top left, but how can I also limit bottom right?

Here's an example: http://jsfiddle.net/ha2t7et2/1/

Basically, I want the map to always be in view.

**Comment by bumbu** [comment]
An example is available [here](http://ariutta.github.io/svg-pan-zoom/demo/limit-pan.html).
