### ISSUE TITLE
How to get pixel coordinate after pan operation in svg-pan-zoom?

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#158]
I can run successfully Forward . The operation is panZoom.panBy({x:-10,y:0}) in my front-end page a.html. And I update your svg-pan-zoom.js and add other js and you can see them below.
svgPanZoom.prototype.panBy = function(point) {
  var viewportCTM = this.viewport.getCTM()
  viewportCTM.e += point.x
  viewportCTM.f += point.y
   this.viewport.setCTM(viewportCTM)  //有个变换在里面的
  if($(".map-tooltip").css("display")=="block")
  {
  var ex=$(".map-tooltip").css("left").split("p");
  var ey=$(".map-tooltip").css("top").split("p");
  var newex=parseFloat(ex[0])+point.x;newex+="px";
  var newey=parseFloat(ey[0])+point.y;newey+="px"; 
  $(".map-tooltip").css("left",newex);
  $(".map-tooltip").css("top", newey);
  }
}
They are OK. tooltip can move as with as panZoom.panBy({x:-10,y:0}) when I trigger the button of page a.html.

But They are failure backward. after I pan the map I need move tooltip as with as map.
My design is   (update handleMouseUp  function )
SvgPanZoom.prototype.handleMouseUp = function(evt) {
  if (this.options.preventMouseEventsDefault) {
    if (evt.preventDefault) {
      evt.preventDefault()
    } else {
      evt.returnValue = false
    }
  }
  if (this.state === 'pan') {
    this.state = 'none';
   
  }

   if($(".map-tooltip").css("display")=="block")
    {     
    var ex=$(".map-tooltip").css("left").split("p");
    var ey=$(".map-tooltip").css("top").split("p");
    console.log("up:"+this.getPan().x+"  "+this.getPan().y +" "+evt.pageX +"  "+evt.pageY+" "+ex[0] +"  "+ey[0]);
    var newex=parseFloat(ex[0])+ this.getPan().x;newex+="px";
    var newey=parseFloat(ey[0])+ this.getPan().y;newey+="px"; 
    $(".map-tooltip").css("left",newex);
    $(".map-tooltip").css("top", newey);  
}.......
}
why can't I use this.getPan().x to get DIV map-tooltip's move length ??

**Comment by liyihongcug** [comment]
The second problem is  :
How to get the DIV tooltip's move length after user zoomin/zoomout your svg map.
I don't know how to add the my code below:
Zoom.prototype.zoomAtPoint = function(zoomScale, point, zoomAbsolute) {
  var originalState = this.viewport.getOriginalState()

  if (!zoomAbsolute) {
    // Fit zoomScale in set bounds
    if (this.getZoom() * zoomScale < this.options.minZoom * originalState.zoom) {
      zoomScale = (this.options.minZoom * originalState.zoom) / this.getZoom()
    } else if (this.getZoom() * zoomScale > this.options.maxZoom * originalState.zoom) {
      zoomScale = (this.options.maxZoom * originalState.zoom) / this.getZoom()
    }
  } else {
    // Fit zoomScale in set bounds
    zoomScale = Math.max(this.options.minZoom * originalState.zoom, Math.min(this.options.maxZoom * originalState.zoom, zoomScale))
    // Find relative scale to achieve desired scale
    zoomScale = zoomScale/this.getZoom()
  }

  var oldCTM = this.viewport.getCTM()
    , relativePoint = point.matrixTransform(oldCTM.inverse())
    , modifier = this.svg.createSVGMatrix().translate(relativePoint.x, relativePoint.y).scale(zoomScale).translate(-relativePoint.x, -relativePoint.y)
    , newCTM = oldCTM.multiply(modifier)

  if (newCTM.a !== oldCTM.a) {
    this.viewport.setCTM(newCTM)
  }
 // alert("wheel"+relativePoint.x);
  /* if($(".mapplic-tooltip").css("display")=="block")
  {................................................................................. How to add my code???

**Comment by liyihongcug** [comment]
I have solved the first problem which is only pan and not zoom in/zoomout.
But I can't get precise location when my operation is only zoom in /zoom out and not pan.
So current problem is : I put one DIV layer on svg map layer how to let DIV layer move as with as map zoom in/zoom out. In other words ,I  need to know DIV layer's location variation rule as with as map zoom. 
var newex=parseFloat(ex[0])+ this.getPan().x;-------------------For only pan and not zoom, It is OK
var newex=parseFloat(ex[0])+ this.getPan().x*CurZoom/LastZOOM; ---------------For only zoom and not pan, it is not precise and when zoom is rather big DIV layer will deviate from right postion so that we know DIV location is not  suitable

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help

**Comment by schester44** [comment]
@liyihongcug did you ever figure this out? I'd love to figure out a div's position relative to the svg when zooming/panning. Still working on a solution at this time.

**Comment by sunnypp** [comment]
I am not sure if I get the question correctly.  I have made a tooltip that points to a shape inside the svg when panning / zooming.  I used ` elem.getBoundingClientRect();` to get the location of the shape and do calculations to move the div, and that "moving div" function is hooked to `onPan` and `onZoom`.
