### ISSUE TITLE
how to get screen coordinate by svg document point 

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#160]
Html codes are:
<div><svg ...></svg></div>

I can get convert mouse screen coordinates to svg document point coordinates .
Codes are below(evt is mouse click event)

var myDragTarget = evt.target;
var pnt = myDragTarget.ownerSVGElement.createSVGPoint();
pnt.x = evt.clientX;pnt.y = evt.clientY;
 var sCTM = myDragTarget.getScreenCTM();
var Pnt = pnt.matrixTransform(sCTM.inverse());

Now I reverse this requirement and at first I know one point coordinate in svg document(
for example ,text is in (121,321)
) and current zoomrate ,panx and pany of svg. And I need know the point's screen coordinate
(e.ClientX)?  
Please make use of codes to explain it.

**Comment by bumbu** [comment]
https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help
