### ISSUE TITLE
How to only show 1/8 of the whole svg

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#161]
My requirement is below:
I split the whole svg map into one <table> (8 sections : 4 <tr> rows,and each row includes 2 <td> sections).
when I click each td tag ,svg should only show 1/8 section of the svg map  of its fixed svg postion.
It seems I need adjust viewbox and but I hope svg-pan-zoom can provide one function to support the function.

**Comment by bumbu** [comment]
You have to compute by yourself the necessary zoom and pan levels. After that use `zoom` and `pan` methods to update the SVG.

https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help
