### ISSUE TITLE
Resizing window and reset button behavior

### ISSUE THREAD

**Issue by prrrnd** [ariutta/svg-pan-zoom#162]
I'm having an issue related to the reset button after resizing the browser window. (Or changing screen orientation on mobile devices)
##### Steps:
* Load the page in a small window.
* Enlarge the window
* Click the reset button.

The SVG is now smaller, and not centered as the reset button uses the original window state.
Am I doing something wrong?

**Comment by calanor** [comment]
You need to call  resize() function when detect that window its resized:
<pre>
$(window).resize(function()  
{
   svgObject.resize();
});
</pre>

**Comment by bumbu** [comment]
@prrrnd as @calanor said - you have to call `resize` so that the library would know that is has to update its internal state.
@calanor Thanks!
