### ISSUE TITLE
e.contentDocument is null error

### ISSUE THREAD

**Issue by monotasker** [ariutta/svg-pan-zoom#164]
Thanks for writing such a great library. I'm just having trouble getting it working. I'm embedding a complex svg as an object. When I call svgPanZoom with the id of the object as selector I get this error:
```
TypeError: e.contentDocument is null
```
I've set up a demo here: http://jsfiddle.net/monotasker/gskfcbmh/

If I try to use the id of the actual svg document ('#svg2') as the selector I get an error saying that the selector doesn't find any matches.

Thanks ahead of time for your help.

**Comment by crauterb** [comment]
Experienced the same problem this morning.
Just seem to be problem within Javascript, wherefore the desired object is still null.
Providing a timeout that waited for the svg to be loaded correctly solved the issue for me.
```javascript
document.getElementById('demo-svg').setAttribute('data','/some/path/');
setTimeout(function() { svgPanZoom('#demo-svg', { zoomEnabled: true, controlIconsEnabled: true}); }, 200 );
```
Sure some other solution with dereffered.done() or somethng are just as viable.
As I am not a Javascript-Pro, feedback on wether some bug persists would be great ;)

**Comment by bumbu** [comment]
As @crauterb said - you have to wait for embedded SVG to load. 
An example is in this [demo](http://ariutta.github.io/svg-pan-zoom/demo/dynamic-load.html)
