### ISSUE TITLE
Control Icons 

### ISSUE THREAD

**Issue by br8kpoint** [ariutta/svg-pan-zoom#170]
Hello,

Great library, saving me a lot of time on my current project.

Can you explain to me why the Control Icon "Reset" is implemented as an svg path rather than a text element?

One of the requirements for our project is to support i18n. A path seems overly complicated verses a text element. 

Also, I am experimenting with setting a control icon scale factor option to bump up the size of the controls on a mobile device.

**Comment by ariutta** [comment]
I originally made the reset button in Illustrator and could only export it
as a path. A solution that allows for better i18n would be great, but I
haven't had time myself to make it happen. I think there's another issue
that was opened regarding this.

**Comment by bumbu** [comment]
Hey, you can implement your own custom controls like in [this demo](http://ariutta.github.io/svg-pan-zoom/demo/custom-controls.html).
