### ISSUE TITLE
Panning on a hyperlink triggers the hyperlink on mouse up

### ISSUE THREAD

**Issue by rustyx** [ariutta/svg-pan-zoom#180]
Normally when I pan something, even if I grab the content by a hyperlink, nothing special happens when I finish panning.
But with svg-pan-zoom, the hyperlink is still activated as soon as the panning is finished.
This should not happen, or at least should be configurable.

**Comment by bumbu** [comment]
There are usecases where blocking `mouseup` event is not desirable. So this will not be added into core. 
A simple for that would be to do something similar to #148 where you can attach `mouseup` event listeners to your hyperlinks. And if `mouseup` would happen before a `mousedrag` then that event can be prevented from executing the default behavior.

**Comment by rustyx** [comment]
Very curious as to what those use cases are.
Furthermore, detecting the 'pan' state is a non-trivial task, and given that the SvgPanZoom's pan state is not exposed, I'm going to have to hack into SvgPanZoom itself to implement this properly.
