### ISSUE TITLE
How to limit the svg element does not excess the container?

### ISSUE THREAD

**Issue by kitkimwong** [ariutta/svg-pan-zoom#182]
How to limit the svg element does not excess the container when user pinch or drag/pan?

**Comment by bumbu** [comment]
I suppose you're asking about [this](https://github.com/ariutta/svg-pan-zoom#keep-content-visiblelimit-pan)

**Comment by kitkimwong** [comment]
@bumbu  Thank you for your answer, but this example will get wrong after i add "viewbox":
          <svg id="limit-svg" xmlns="http://www.w3.org/2000/svg" viewbox = "0 0 602 420"  style="display: inline; width: inherit; min-width: inherit; max-width: inherit; height: inherit; min-height: inherit; max-height: inherit;" version="1.1">

**Comment by bumbu** [comment]
Please add [a reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues).
