### ISSUE TITLE
Show wrappers on README?

### ISSUE THREAD

**Issue by ariutta** [ariutta/svg-pan-zoom#184]
Hi @bumbu,

Thanks for your work maintaining this.

What do you think about adding links on the README to wrappers? I found a few recently:
- Angular: https://www.npmjs.com/package/angular-svg-pan-zoom
- Meteor: https://github.com/jossoco/meteor-svg-pan-zoom/
- R: https://github.com/timelyportfolio/svgPanZoom
- Ruby: https://rubygems.org/gems/svg_pan_zoom
- maybe others I haven't seen...

**Comment by bumbu** [comment]
Sure, why not.
