### ISSUE TITLE
Zoom limit not recalculated when container resizes

### ISSUE THREAD

**Issue by kevinlaw91** [ariutta/svg-pan-zoom#185]
I have a page that **automatically adjust** SVG container size when window re-sizes. I also set the `minZoom` and `maxZoom` property for svgpanzoom.

I opened the page in a small window, when I re-size the window (e.g. maximize), the zoom limit does not gets recalculated uisng the newer, bigger container size. My artwork remain in a very small size even when fully zoomed in.

> When I zoom in fully to the limit, and maximize a window from a small window...
> **What I expect:**
> Since container is bigger now, I can zoom in deeper, thus artwork can become bigger
> 
> **What I see:**
> I cannot zoom in further.
> It looks like the zoom level is restricted to the original container size, not the current size

If this sounds confusing, try to imagine if the original window/container size is 200x200, the artwork is fitted and sized to 200x200 when load. I can zoom for example 200% to 400x400 at max.
When I maximize the window/container to 1000x1000, I expect the artwork can zoom in to become 2000x2000 size, but it doesn't allow me to do so. The artwork is still fully zoomed in at 400x400 in a 1000x1000 container, I cannot zoom in futher.

This is fixed when I reload the page in maximized state. i.e., I can zoom in to 2000x2000 in maximized window with 1000x1000 container

**Comment by bumbu** [comment]
Did you try calling `.resize()` on svgPanZoom instance after browser resize? There is a demo with that.
If this doesn't help then please check provide a reproducible example https://github.com/ariutta/svg-pan-zoom#support with required steps.

**Comment by kevinlaw91** [comment]
Hi @bumbu, I did call resize() but issue is still there.

I found that it is hard to demo the bug using jsfiddle because we need to react with window resize event. I made a gist instead: https://gist.github.com/kevinlaw91/82d9b7d0ebf00c2120ca

You can download and run in browser, then use **inspect element(docked)** to trigger window `resize` event. I also created screenshot and steps on how to reproduce the bug:
[issue185.pdf](https://github.com/ariutta/svg-pan-zoom/files/141149/issue185.pdf)

**Comment by schurin** [comment]
I have a similar problem.
Chrome: 48.0.2564.116 m
SvgPanZoom: 3.2.6
When I resize of the container, contents of the container does not fit, and extends beyond the boundaries.
The content is still the same size as it was before resize. I watched the zoom ratio before and after resize - _panZoom.getSizes().realZoom. And they were equal.
SvgPanZoom v3.2.3
We use this version.
Behavior to resize different from v3.2.6
When you resize the content to be fit.
But, when i call - _panZoom.zoomOut(), I'll get the content size before to resize
I'm use methods resize->fit->center when changing the size of the container.

**Comment by MarioDabrowski** [comment]
Same issue here, any ETA on merging the fix?
