### ISSUE TITLE
Image not centered when zooming

### ISSUE THREAD

**Issue by darrensw777** [ariutta/svg-pan-zoom#186]
I'm having an issue where zooming does not center on a point as it's supposed to.

Basically, I hold the mouse over a point in the image and although it zooms ok, it is not centered and the point I held my mouse over moves off in a diagonal direction.

My question is, what within the SVG might cause this?

I can't share the SVG unfortunately as it's a government project.

Any clues to solving this would be appreciated. 

I'm using basic instantiation: `mapPanZoom = svgPanZoom('svg');`

It's worth mentioning that I have tried with a less feature rich jQuery plug in and that works ok as far as centering goes.

**Comment by bumbu** [comment]
Unfortunately without an example we can't do anything as our basic examples work. 
If you can't share the entire SVG maybe you can remove all the sensitive information from it and use some dummy content?
