### ISSUE TITLE
Uncaught Error: Module name "uniwheel" has not been loaded yet for context

### ISSUE THREAD

**Issue by gregtampa** [ariutta/svg-pan-zoom#193]
Uncaught Error: Module name "uniwheel" has not been loaded yet for context: _. Use require([])

**http://requirejs.org/docs/errors.html#notloaded
makeError @ require.js:166
localRequire @ require.js:1407
requirejs @ require.js:1752
(anonymous function) @ svg-pan-zoom.js:1**

[](http://requirejs.org/docs/errors.html)

The limitation relates to the simplified CommonJS syntax vs. the normal callback syntax:

http://requirejs.org/docs/whyamd.html#commonjscompat
https://github.com/jrburke/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define

Loading a module is inherently an asynchronous process due to the unknown timing of downloading it. However, RequireJS in emulation of the server-side CommonJS spec tries to give you a simplified syntax. When you do something like this:

```
var foomodule = require('foo');
// do something with fooModule
```

What's happening behind the scenes is that RequireJS is looking at the body of your function code and parsing out that you need 'foo' and loading it prior to your function execution. However, when a variable or anything other than a simple string, such as your example...

`var module = require(path); // Call RequireJS require`
...

then Require is unable to parse this out and automatically convert it. The solution is to convert to the callback syntax;

```
var moduleName = 'foo';
require([moduleName], function(fooModule){
    // do something with fooModule
})
```

Given the above hopefully you can solve the issue.

**Comment by bumbu** [comment]
When using Require.js you should load the compiled library (and not the source files). 
Check [Require.js demo](http://ariutta.github.io/svg-pan-zoom/demo/require.html) and the [source file](http://ariutta.github.io/svg-pan-zoom/demo/require-main.js).
