### ISSUE TITLE
how to delete svgpanzoom object

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#197]
when I use window.zoomTiger = svgPanZoom(mySVG, ---
and at the end of the task I need drop the svgPanZoom in order to delete <g id="viewport..." and <g id="svg-pan-zoom-zoom-out" and so on.

I can't find the way from pugin. Can u help me provide the function?  (This function can drop all <g id="viewport..." and <g id="svg-pan-zoom-zoom-out" and so on. and don't update other native SVg content)

**Comment by bumbu** [comment]
You can destroy svgPanZoom instance by using [`destroy` method](https://github.com/ariutta/svg-pan-zoom#public-api). 

If you want to remove the SVG element or some of its inner elements than this library is not for that. You can use [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help) for such types of questions.
