### ISSUE TITLE
Transforms no longer work in IE/Edge

### ISSUE THREAD

**Issue by richardszalay** [ariutta/svg-pan-zoom#198]
IE/Edge has a bug whereby CSS transforms don't work, but attribute based transforms do. The commits introduced by #195 moved entirely to CSS transforms, and thus things stopped working in IE.

http://caniuse.com/#feat=transforms2d
https://connect.microsoft.com/IE/feedback/details/811744/ie11-bug-with-implementation-of-css-transforms-in-svg

**Comment by greggbjensen** [comment]
I am running into this same issue in IE.  The transform attribute works, but not the style.

**Comment by greggbjensen** [comment]
I went back to 3.2.6, and that one works fine as @richardszalay mentioned.

**Comment by bumbu** [comment]
I kept CSS transforms but also added attribute transforms. Seems to work well while also allowing CSS animations.
