### ISSUE TITLE
how to get clientX,clientY in your demo/mobile.html in smart phone?

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#200]
Thanks for demo/mobile.html which use harmmer.js in smart phone.
Now I need get  clientX,clientY to generate new svg point in smart phone in order to get real coordate of svg.
But harmmer.js only provide to ev.deltaX, ev.deltaY.  (why it is always =0)
 this.hammer.on('doubletap', function(ev){
              instance.zoomIn();
              console.log(ev.deltaX);console.log(ev.deltaY);---------------0   0

My Android use corvoda 3.4.  (Can you provide the way to get mouse double-tap's real coordinate in smart phone webview of mobile)

**Comment by bumbu** [comment]
This doesn't seem to be a svg-pan-zom issue, so please use [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help) for such questions
