### ISSUE TITLE
Moving to CSS transform causes getBoundingClientRect() to return incorrect values

### ISSUE THREAD

**Issue by kevinlaw91** [ariutta/svg-pan-zoom#201]
This bug appears in Firefox 46 after the library changed to use CSS transform. Existing code that call `getBoundingClientRect()` on an `<svg>` element will get incorrect values.

Please see this Firefox bug report:
[Bug 1066435 - getBoundingClientRect() doesn't take CSS transform into account for SVG elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1066435)

**Comment by bumbu** [comment]
Should be fixed in 3.2.9
