### ISSUE TITLE
why don't inonic support svg-pan-zoom

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#202]
I am ready for svg-pan-zoom.js in ionic-lab.

But I find codes  can't run below
 angular.module('starter', ['ionic'])
 .run(function($ionicPlatform) {
      $ionicPlatform.ready(function() {
        // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
        // for form inputs)
        if(window.cordova && window.cordova.plugins.Keyboard) {
          cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        if(window.StatusBar) {
          // org.apache.cordova.statusbar required
          StatusBar.styleDefault();
        }
      });
    })
.config(function($stateProvider, $urlRouterProvider) {
      $stateProvider
        .state('app', {
          url: "/app",
          abstract: true,
          templateUrl: "menu.html",
          controller: 'AppCtrl'
        })
})
 .controller('AppCtrl', function($scope) {
    window.panZoom = svgPanZoom('#mobile-svg', {
          zoomEnabled: true
        , controlIconsEnabled: true
        , fit: 1
        , center: 1
        //, customEventsHandler: eventsHandler
        });

The error starts in window.panZoom = svgPanZoom('#mobile-svg', 
how to solve it?>

**Comment by bumbu** [comment]
Sorry, but this example is not [reproducible](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues).
At least an error stack trace would be useful. 

Some things to look at are:
* If your SVG available in DOM at the time when you call `svgPanZoom`
* If you don't use inline SVG (you reference SVG contents via `src` attribute) they you should call `svgPanZoom` function only after that SVG is loaded. 

Also check _dynamic-load_ demo to get an idea how to handle dynamically loaded SVGs.
