### ISSUE TITLE
white area over the svg

### ISSUE THREAD

**Issue by MargheritaRossi** [ariutta/svg-pan-zoom#203]
First, I love this! It's the only thing that works on my code ahah! there's only one problem, I've a white area over my svg and I don't  know how to fix it! 
I tried to change the code, I found that this part is the problem, in particular "fit" and "center":

 // Expose to window namespace for testing purposes
       window.panZoom = svgPanZoom('#mobile-svg', {
          zoomEnabled: true
        , controlIconsEnabled: false //abilita e disabilita le icone dello zoom
        , fit: 1
        , center: 1
        , customEventsHandler: eventsHandler
        });

how should I modify it?

![nonva1](https://cloud.githubusercontent.com/assets/9364730/15755211/132724ee-28fc-11e6-8fdf-e24aed11bddb.JPG)

**Comment by bumbu** [comment]
If it is a bug then please provide a [reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues).
For generic questions please use [StackOverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help).
