### ISSUE TITLE
Center

### ISSUE THREAD

**Issue by Arvidas1** [ariutta/svg-pan-zoom#210]
Здравствуйте!
Инициализирую объект следующим образом:
        var $svg = $('svg');
        $svg.width("100%").height("100%");

        panZoomSection = svgPanZoom('svg', {
            controlIconsEnabled: false
            , zoomScaleSensitivity: 0.05
            , minZoom: 0.1
            , maxZoom: 100
        });

        panZoomSection.updateBBox();
        panZoomSection.fit();
Если я потом делаю вызов функции center на объекте panZoomSection, то svg смещается вправо и вниз, а не центрируется. Подскажите, пожалуйста, в чем может быть ошибка.

Hello!
I initialize the object as follows:
         var $ svg = $ ( 'svg');
         $ Svg.width ( "100%") height ( "100%.");

         panZoomSection = svgPanZoom ( 'svg', {
             controlIconsEnabled: false
             , ZoomScaleSensitivity: 0.05
             , MinZoom: 0.1
             , MaxZoom: 100
         });

         panZoomSection.updateBBox ();
         panZoomSection.fit ();
If I make call of center function on panZoomSection object, svg is shifted to the right and down, not centered. Tell me, please, what error can cause such behaviour.

**Comment by bumbu** [comment]
If you feel that it's a bug then please provide a [reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues). 

Otherwise please post your question on [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help)
