### ISSUE TITLE
Transition property not working in IE11?

### ISSUE THREAD

**Issue by simonmacfadyen** [ariutta/svg-pan-zoom#211]
Hi there,

I have a transition on the viewport (Latest release), as following:

```
.svg-pan-zoom_viewport {
    -webkit-transition: all 600ms cubic-bezier(0.165, 0.84, 0.44, 1);
    transition:         all 600ms cubic-bezier(0.165, 0.84, 0.44, 1);
}
```

Sadly, IE11 doesn't seem to transition this at all. Have you experienced this bug with IE?

**Comment by bumbu** [comment]
Most probably this was a bug with a previous plugin version. Version 3.2.9 seems to work fine.
