### ISSUE TITLE
Is there any library whith wich i can animate a svg with pan/zoom

### ISSUE THREAD

**Issue by FrankenApps** [ariutta/svg-pan-zoom#213]
I have a svg on which i used pan/zoom, and now i tried to make some elements of the svg follow certain paths (i used d3.js in this case, but i used the native <animatePath>, too). Now what happens is that the animated objects either do not respond to zooming (they stay big), or they do not follow the path, they move where the path would normally have been... For illustration I added this screenshot, where I used d3.js for animation (note that the car should be on that little test road, as big as the other cars in the picture): 
![svg_game_bug](https://cloud.githubusercontent.com/assets/17967303/17372071/8de0a530-59a2-11e6-8486-27a5d5cd210f.png)
It does however follow the path and move...

Now my question is if there is any method (to make a svg element follow a given path), that I can use together with svg-pan-zoom, without running into issues.

**Comment by bumbu** [comment]
Please ask your questions that are not directly related to the library on StackOverflow.
If you still think that this is a library issue then please provide a [reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues)
