### ISSUE TITLE
3.2.8 doesn't work in IE

### ISSUE THREAD

**Issue by lipsumar** [ariutta/svg-pan-zoom#214]
Only tested IE11 and 10 but I lost 2 days on this, I thought I'd put this here :)  
No error and the inspector will show you a `matrix` being correctly updated but nothing changes visually.

Switching to 3.2.5 fixed it all.

**Comment by ariutta** [comment]
Sorry, that sounds frustrating :(

Any suggestions for a test to catch things like this?

**Comment by ariutta** [comment]
Also, did you try 3.2.9?
