### ISSUE TITLE
Can you explain this path?

### ISSUE THREAD

**Issue by liyihongcug** [ariutta/svg-pan-zoom#216]
path id="batman-path22"  center="22.395,127.223" height="4"  style="fill:rgb(0,0,0)" d="M22.395-127.223c-4.492,11.344-4.688,33.75,0,44.883c-11.328-4.492-33.656-4.579-44.789,0.109c4.491-11.354,4.688-33.75,0-44.892C-11.066-122.63,11.262-122.536,22.395-127.223Z"

This path is right. But I don't understand its grammar.
(I point it out I have much experience in svg)  .I can understandpath = "M550.1 163.4 L576.5 170.5 L579.4 174.8 L606 169.6 L641.3 181.3 L669 220.2 L593.7 236.1 L584.9 222.6 L595.2 220.5 L586.2 206.7 L539.8 216.1 L524.8 239.1 L471.9 250.1 L461.4 231.3 L471.1 229.4 L464.8 218.1 L455.1 220.1 L435.6 185.1 Z";
			
Now back to question." M22.395-127.223c-4.492,11.344-4.688,33.75,0,44.883c......."
Herer  “- ” stands for  space character ? But I replace all and at last I find it is error.
So I Put it out and I want to know   "M22.395-127.223c-4.492,11.344-4.688,33.75,0,44.883c"
M  -  c   C  what means?

**Comment by liyihongcug** [comment]
solved .  Reglar expression in Java.
The answer is M
22.395,-127.223
c
-4.492,11.344,-4.688,33.75,0,44.883.

Now next question ,inverse.
Common path ,""M550.1 163.4 L576.5 170.5 L579.4 174.8 L606 169.6 L641.3 181.3 L669 220.2 L593.7 236.1 L584.9 222.6 L595.2 220.5 L586.2 206.7 L539.8 216.1 L524.8 239.1 L471.9 250.1 L461.4 231.3 L471.1 229.4 L464.8 218.1 L455.1 220.1 L435.6 185.1 Z";"
How to transfer  the format of "M22.395-127.223c-4.492,11.344-4.688,33.75,0,44.883c"

**Comment by ariutta** [comment]
Is this a bug report? If it's a "how to use" question for svg-pan-zoom or a general SVG question, your best bet is asking at stackoverflow.
