### ISSUE TITLE
Make Pan button configurable

### ISSUE THREAD

**Issue by haykpetros** [ariutta/svg-pan-zoom#218]
Hi,

There are situations when Plugin needs to be used with some other Plugins / Code that needs Mouse Left Button for it's own operations. So I suggest adding "panButton" option to make it configurable. If it is OK I can create a pull request with implementation.

Thanks

**Comment by bumbu** [comment]
Hi, 

Thanks for suggestion. 
Currently you can achieve that using:
* [Custom event handlers](https://github.com/ariutta/svg-pan-zoom#custom-events-support)
* Custom controls

You can find examples how to use them in `demo` folder.

**Comment by eevleevs** [comment]
https://stackoverflow.com/questions/41040866/svgpanzoom-only-pan-using-middle-mouse-button
