### ISSUE TITLE
DefinitelyTyped Pull Request (typings definition 3.3.0)

### ISSUE THREAD

**Issue by Yimiprod** [ariutta/svg-pan-zoom#225]
Hi @ariutta 
I've made a pull request here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12448
Can you can look at it and let me know if i missed something please ?

**Comment by ariutta** [comment]
Hi @Yimiprod,

Thanks for doing this! Based on a quick review, it looks good to me. A minor thing, but `IPoint` could be simply `Point` (See [Do not use "I" as a prefix for interface names.](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names)).

@bumbu is leading development now, so he may have additional comments. I'll leave this open for a bit to give him a chance to give any feedback.

**Comment by bumbu** [comment]
Hey @Yimiprod  - nice work!

Looks good to me. Unfortunately I don't actively use TypeScript, so I can't help much here. After a quick scan - your PR improves existing definition for the library (which I didn't even know that exists 😄).

**Comment by Yimiprod** [comment]
Updated `IPoint` to `Point`, thanks both of you.

**Comment by ariutta** [comment]
Would it make sense to have the `.d.ts` file included in this repo? If so, would you be interested in maintaining it? I can make you a collaborator on this repo.

**Comment by Yimiprod** [comment]
@ariutta why not, i'm ok with this.

**Comment by ariutta** [comment]
Great, thanks! I'll add you as a contributor and close this issue. The TS declarations file is yours to control as you see fit.

You're also welcome to refactor the codebase and respond to issues if you like. I'd just ask that you give @bumbu or me a chance to weigh in on non-trivial changes to the codebase before you merge them into master. (If we're both MIA for 2 weeks, just go ahead.)
