### ISSUE TITLE
thumbnailViewer can't support the inline svg

### ISSUE THREAD

**Issue by tedwong** [ariutta/svg-pan-zoom#227]
Bug report
---

### Expected behaviour
Assigning inline svg element can do the thumbnailViewer. 

### Actual behaviour
`Provided selector is not an HTML object nor String` occurred.

### Steps to reproduce the behaviour

1. Assign two svg element to the thumbnailViewer method. 

### Configuration

- svg-pan-zoom version: 3.4.0
- Browser(s): Chrome Version 54.0.2840.98 (64-bit)
- Operating system(s): macOS 10.12.1
- A relevant example URL: NA

**Comment by bumbu** [comment]
I just tested it locally - and it works perfectly fine with inline SVGs. 
I can't get it working on jsFiddle - so I'll not post the example here (but I tried).

The error message is from svg-pan-zoom and it's telling you that you didn't initialize the plugin correctly. So it is not a bug.
The thumbnail plugin doesn't make part of the core - so even if that would be a bug, it would have a minor priority as thumbnail plugin is a demo of how you can use svg-pan-zoom - and should be used without assuming any responsibility from its author/s.

**Comment by mangowi** [comment]
> I just tested it locally - and it works perfectly fine with inline SVGs.
> I can't get it working on jsFiddle - so I'll not post the example here (but I tried).
> 
> The error message is from svg-pan-zoom and it's telling you that you didn't initialize the plugin correctly. So _it is not a bug_.
> The thumbnail plugin doesn't make part of the core - so even if that would be a bug, it would have a minor priority as thumbnail plugin is a demo of how you can use svg-pan-zoom - and should be used without assuming any responsibility from its author/s.
> 
> Also next time please provide a reproducible example as it makes debugging much easier and faster.

Hello @bumbu 
Can you please share the example on how to use inline SVG for thumbnailViewer demo.
Thank you in advance :)

**Comment by bumbu** [comment]
Hey @mangowi, 
The [thumbnail viewer demo](https://github.com/ariutta/svg-pan-zoom/blob/master/demo/thumbnailViewer.html) uses an in-line SVG.

**Comment by mangowi** [comment]
Thanks @bumbu
