### ISSUE TITLE
Is there support for zoom on drag (esp. 3-finger drag on mac) and defer pan to scrollbars?

### ISSUE THREAD

**Issue by bluejamesbond** [ariutta/svg-pan-zoom#228]

**Comment by bumbu** [comment]
As you can see from documentation - there are no such things. 
You can see how to enable custom events in _Custom events: Touch events support: pan, double tap, pinch_ demo. 

Please, in future for such questions use [StackOverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help).
