### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by julmot** [ariutta/svg-pan-zoom#231]
Make it available, e.g. on [jsDelivr](http://www.jsdelivr.com/).

**Comment by bumbu** [comment]
I do not have experience with that. If there is anyone who wants to be responsible for that (at least doing all the initial work and ideally adding a script to `package.json` to have it work automagically) - that would be great. @julmot do you have any experience with that?

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/

**Comment by bumbu** [comment]
Thank you @jimaek 
I'm going to update the readme
