### ISSUE TITLE
Content not updated

### ISSUE THREAD

**Issue by geert-b** [ariutta/svg-pan-zoom#233]
Hi,

When I add new content to the .svg-pan-zoom_viewport group it is not visible on the page. My code works when I don't enable the pan/zoom plugin.
I now use an ugly hack:
`$('.svg-pan-zoom_viewport').html($('.svg-pan-zoom_viewport').html());`
This just re-pasts the entire html content. But why isn't it possible to just add new content to the svg without taking this extra step?

**Comment by bumbu** [comment]
Issue doesn't follow [issue guidelines](https://github.com/ariutta/svg-pan-zoom/blob/master/ISSUE_TEMPLATE.md). Closing until issue is updated.
