### ISSUE TITLE
Zoom triggers beforePan before updating CTM

### ISSUE THREAD

**Issue by AndrolGenhald** [ariutta/svg-pan-zoom#235]
### Expected behaviour
Zoom updates the CTM then triggers pan, sequence of events should be:

1. beforeZoom()
2. //CTM updated
3. onZoom()
4. beforePan()
5. //CTM updated
6. onPan()

### Actual behaviour
beforePan gets called with the current CTM before it is updated by the zoom:

1. beforeZoom()
2. beforePan()
3. //CTM updated
4. onZoom()
5. onPan()

### Why this is an issue
beforePan allows returning a custom x, y object to pan to, if the CTM isn't updated by zooming before beforePan gets called the custom pan cannot take the zoom into account.
I made a [jsfiddle](https://jsfiddle.net/r6ybb92n/2/) to limit panning to half the viewport width/height (ie if you pan all the way to the bottom right, it limits it so that the svg is in the top left quarter of the viewport). When zooming the svg gets panned to the wrong location.

### Steps to reproduce the behaviour
1. Load the [jsfiddle](https://jsfiddle.net/r6ybb92n/2/)
2. Zoom on the svg
3. The svg is now panned to the wrong location

### Configuration
- svg-pan-zoom version: `3.4.1`

**Comment by bumbu** [comment]
Hi @AndrolGenhald ,

Thank you for the issue. I totally agree with you that this behaviour may be confusing. 
It is somehow a similar issue with #121 but as I see fixing that one will not help with your issue. 

It is definitely a nice-to-have behaviour, and if you manage to make it working - a pull-request is more then welcome!

**Comment by AndrolGenhald** [comment]
I'm planning to get around to it hopefully sometime next week.
