### ISSUE TITLE
Restricting min width/height of content to size of viewport.

### ISSUE THREAD

**Issue by brandondurham** [ariutta/svg-pan-zoom#240]
Wasn’t sure where to put this, so let me know if there is a better place! Wanted to share a solution for something I couldn’t find the answer to.

I needed a way to have the `<g />` default to filling the viewport, even if it meant one dimension overflows (essentially the same affect that `background-size: cover;` has in CSS). In addition, I needed pan coordinates to be ensure none of the four sides of the `<g />` ever enter the interior of the viewport. Basically `x` and `y` can never have positive values.

This is what I ended up using:

```javascript
let art = null;

const beforePan = (oldPan, newPan) => {
	const sizes = art.getSizes();

	// Multiply viewbox width of SVG by current zoom and subtract
	// viewport width to get amount of overflown SVG.
	const x = -((sizes.viewBox.width * sizes.realZoom) - sizes.width);

	// Multiply viewbox height of SVG by current zoom and subtract
	// viewport height to get amount of overflown SVG.
	const y = -((sizes.viewBox.height * sizes.realZoom) - sizes.height);

	// Determine what’s lower, the current drag x/y coords or zero
	const minx = Math.min(0, newPan.x);
	const miny = Math.min(0, newPan.y);

	return {
		x: Math.max(x, minx),
		y: Math.max(y, miny)
	};
};

// Expose to window namespace for testing purposes
art = svgPanZoom('#wrapper', {
	beforePan,
	center: true,
	contain: true,
	fit: false,
	mouseWheelZoomEnabled: false,
	zoomEnabled: true
});
```

Hope this helps someone else!

**Comment by bumbu** [comment]
Hi @brandondurham 

Thank you for your solution to the problem. I also don't know where we could store such stuff, so let it be in issues. 

I'll close the issue, but whoever needs it can easily find it through search.
