### ISSUE TITLE
Svg with viewbox attribute using with svg-pan-zoom

### ISSUE THREAD

**Issue by andrei-kondakov** [ariutta/svg-pan-zoom#244]
I have the svg-map with viewbox attribute (thats need me to fit map in div container):
```
<svg id='iso-map' viewBox="0 0 1248 827" preserveAspectRatio="xMidYMid meet">
path and etc...
</svg>
```
![map](https://cloud.githubusercontent.com/assets/10554164/25894779/ec70f5e0-3585-11e7-974f-bb763e7bd14b.png)
I want to use **svg-pan-zoom.js** library to add zoom and pan to my map. After execute following code:
```
var svgElement = d3.select($element[0]).select("svg");
var panZoomTiger = svgPanZoom(svgElement.node());
```
Attribute _viewbox_ is removed from my svg element and I have following pic:
![map2](https://cloud.githubusercontent.com/assets/10554164/25894899/5c6a139a-3586-11e7-86e8-e1d3af0ca566.png)
![map3](https://cloud.githubusercontent.com/assets/10554164/25894901/5e3ab90e-3586-11e7-8f05-193abe176501.png)

I tried programmatically to add the attribute after use svgPanZoom and my map showed in full size but pan and zoom works incorrectly:

```
var svgElement = d3.select($element[0]).select("svg");
var panZoomTiger = svgPanZoom(svgElement.node());
svgElement.attr("viewBox", "0 0 1248 827");
```

Is it bug or what I am doing wrong?

**Comment by bumbu** [comment]
Please read the section about [Bugs and issues](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues).

I'm going to close this issue, and you may get some help in the [issue you opened on stackoverflow](http://stackoverflow.com/questions/43880286/svg-with-viewbox-attribute-using-with-svg-pan-zoom). To get a better chance at that - please provide a reproducible example.

**Comment by FrazerDH** [comment]
@andrei-kondakov - did you ever resolve this? I'm facing the exact same issue.

**Comment by dominikfilkus** [comment]
Same issue here. No solutions found yet.
