### ISSUE TITLE
[Safari] Mouse wheel zooming doesn't work outside the viewport area

### ISSUE THREAD

**Issue by dhqvinh** [ariutta/svg-pan-zoom#245]
On Safari, mouse wheel zooming doesn't work outside the viewport area.
---

### Expected behaviour
Mouse wheel zooming feature should work on the entire area of the svg.

### Actual behaviour
Mouse wheel zooming works fine on the viewport area, but it doesn't work outside.

### Steps to reproduce the behaviour

1. Opening a this [demo url](http://ariutta.github.io/svg-pan-zoom/demo/inline.html) in Safari
2. Using the mouse wheel to zoom in / out the svg. It works if the pointer is inside the viewport area, but doesn't zoom when moving the pointer outside.

### Configuration

- svg-pan-zoom version: `3.5.1`
- Browser(s): `Safari 10.1.1` on Mac Mini
- Operating system(s): `OS X 10.11.6`
- Please refer to the image attached below.
![selection_073](https://cloud.githubusercontent.com/assets/1647521/26444878/5ca116d6-4168-11e7-8df9-a7bc91d44e3b.png)

**Comment by dhqvinh** [comment]
This is not an issue of the svg-pan-zoom library itself but a Safari bug. The Mac OS X browser does not dispatch wheel events to the SVG element when there is no SVG content under the pointer.

I followed a workaround from [this issue](https://github.com/d3/d3/issues/3035) by adding a transparent rect element into the SVG content and it did the trick:
`<rect width="100%" height="100%" fill="none"></rect>`

It sounds a little bit tricky, but at least it works!

**Comment by bumbu** [comment]
@dhqvinh Thank you for the insight and a solution!

**Comment by karlcow** [comment]
https://bugs.webkit.org/show_bug.cgi?id=226683
