### ISSUE TITLE
for dynamically appended svg, im getting this error

### ISSUE THREAD

**Issue by sharpvarun** [ariutta/svg-pan-zoom#247]
Uncaught DOMException: Failed to execute 'inverse' on 'SVGMatrix': The matrix is not invertible.
    at SvgPanZoom.zoomAtPoint (http://localhost/school/js/svg-pan-zoom.js:753:52)
    at SvgPanZoom.handleMouseWheel (http://localhost/school/js/svg-pan-zoom.js:724:8)
    at SVGSVGElement.wheelListener (http://localhost/school/js/svg-pan-zoom.js:667:19)

observation: initial transform matrix is setting to zero, here's how it's setting: transform="matrix(0,0,0,0,0,0)"

svg is appended like this:
//html
<div id="limit-div" style="width: 699.16px; height: 420px; border:1px solid black; margin: 0;padding: 
  </div>

//  JS
var xhr = new XMLHttpRequest;
xhr.open('get','assets/map_svgs/Grade_1_and2_Map.svg',true);
xhr.onreadystatechange = function(){
  if (xhr.readyState != 4) return;
  var svg = xhr.responseXML.documentElement;
  svg = document.importNode(svg,true); // surprisingly optional in these browsers
  $('#limit-div').html(svg); 
     var beforePan

        beforePan = function(oldPan, newPan){
          var stopHorizontal = true
            , stopVertical = true
            , gutterWidth = 699.16
            , gutterHeight = 420
              // Computed variables
            , sizes = this.getSizes()
            , leftLimit = -((sizes.viewBox.x + sizes.viewBox.width) * sizes.realZoom) + gutterWidth
            , rightLimit = sizes.width - gutterWidth - (sizes.viewBox.x * sizes.realZoom)
            , topLimit = -((sizes.viewBox.y + sizes.viewBox.height) * sizes.realZoom) + gutterHeight
            , bottomLimit = sizes.height - gutterHeight - (sizes.viewBox.y * sizes.realZoom)

          customPan = {}
          customPan.x = Math.max(leftLimit, Math.min(rightLimit, newPan.x))
          customPan.y = Math.max(topLimit, Math.min(bottomLimit, newPan.y))

          return customPan
        }
        var zoomOut;
        zoomOut = function(){
           
        }
        // Expose to window namespace for testing purposes
        window.panZoom = svgPanZoom('#limit-svg', {
          zoomEnabled: true,
          minZoom: 1,
          maxZoom: 10,
          fit: true,
          beforePan: beforePan,
          onZoom: zoomOut
        });

        var panZoomTiger = svgPanZoom('#limit-svg');

        function zoomTerm(coordinates){

                var animationTime = 1000 // ms
                , animationStepTime = 15 // one frame per 30 ms
                , animationSteps = animationTime / animationStepTime
                , animationStep = 0
                , intervalID = null
                , stepX = 1 / animationSteps
                , panX = coordinates.x
                , panY = coordinates.y

                  intervalID = setInterval(function(){
                    if (animationStep++ < animationSteps) {
                        console.debug('1+stepX: ',1+stepX)
                      panZoomTiger.zoomAtPointBy(1+stepX, {x: panX, y: panY})
                      
                    } else {
                      // Cancel interval
                      clearInterval(intervalID)
                    }
                  }, animationStepTime)    
        }
 
       
};
xhr.send();

**Comment by bumbu** [comment]
Hi, 

Please read the [support](https://github.com/ariutta/svg-pan-zoom#support) section of the Readme. 
Also check the [dynamic loading demo](http://ariutta.github.io/svg-pan-zoom/demo/dynamic-load.html).

**Comment by sharpvarun** [comment]
I got it working, actually the problem was outside container of the SVG was
hidden, but I didn't understand the logic, why should it throw matrix
inversion error when it's hidden. In the console, a message should be
logged saying SVG is hidden.

**Comment by bumbu** [comment]
That depends on the browser implementation, some browsers are detaching foreign objects (like iframe, svg) when an ancestors is hidden. It would be possible for the library to check at any event that all parent elements are visible, but that's computationally inefficient and too specific. The developer should be responsible for knowing when to initialise the library. 

Also see [this comment](https://github.com/ariutta/svg-pan-zoom/issues/105#issuecomment-86380458).

**Comment by sharpvarun** [comment]
Ok.
Thanks for the reply and the awesome library.

**Comment by jacobwindsor** [comment]
I had this same issue when SVG mounted to DOM and fixed it by just giving a height and width to the container. Any value works it seems, even %

**Comment by m-podlesny** [comment]
Thanks for inspiration @jacobwindsor. What was working for me is:
```tsx
// view.tsx
      <div className={classes.container} ref={setRef}>
        <svg viewBox={`0 0 ${width} ${height}`} style={{ width, height }}>
          <g className="svg-pan-zoom_viewport">
            <image x="0" y="0" xlinkHref={url} width={width} height={height} />
          </g>
        </svg>
      </div>
```
* `classes.container` has `width: "100%"` and `height: "100%"` CSS props, but it wasn't enough in my case.
* `setRef` creates the `ref` from which some React hook/helper reads the rendered size in pixels, that are available by `width` and `height` variables (given to the `svg` and `image` elements)

**Comment by HammadManzoor** [comment]
Faced the same issue. The problem occurs when you try to use reset when the container for the svg is not visible on the viewport. I fixed it by checking for this before performing reset.

` const divElement = this.el.nativeElement.querySelector(
      '#myContainer'
    );
    if (divElement) {
      const viewportHeight = window.innerHeight;
      const divOffset = divElement.getBoundingClientRect().top;
      // Check if the div is in the viewport
      if (divOffset < viewportHeight) {
              this.svgPanZoom.resize();
              this.svgPanZoom.reset();
          }
     }
`
