### ISSUE TITLE
svg-pan-zoom slow on android

### ISSUE THREAD

**Issue by murialex** [ariutta/svg-pan-zoom#248]
First of all, svg-pan-zoom is a werry good script, congratulations! I try to implement it on: http://www.geogra.ro/joc/panzoom/ 
Everything is working smooth an fine on windows and IOS browsers but on android, panning and zooming get werry slow with lags.
Can you help me to figure out what is the problem?
Thank You!

**Comment by bumbu** [comment]
Hi, 

The library doesn't do much, and it tries to be as optimal as possible. 
The only easy thing to try is to use `refreshRate` option for Android devices. You can pass it a smaller number (say 10 refreshes per second), there will still be some lag, but the app should become more responsive. 

Try first using a very simple SVG (with not many nodes) and see how it works on troublesome devices.
I'd recommend using a profiler and finding what's the bottleneck in your application. It may be the library, it may be simply the size/complexity of SVG, or maybe the hammer.js responds slower on that particular Android device,  may be something else on your page (like the question mark animation) or all together. Then you'll know what exactly has to be fixed. 

For more help, please refer to [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help).
