### ISSUE TITLE
Multitouch (two or more 'fingers') during pan creates flickering effect

### ISSUE THREAD

**Issue by KoenkookpotPlasmans** [ariutta/svg-pan-zoom#251]
Bug report
---

### Expected behaviour
When multitouch is performed, the expected behaviour is that only the first 'finger' is used for panning. All other touches are ignored. The panning is smooth and creates not flickering effect (switching very quickly between two or more pannings).

### Actual behaviour
When multitouch is performed, the actual behaviour is that all touches are processed and a panning for each touch is performed very quickly behind each other. This creates a flickering effect (switching very quickly between two or more pannings).

### Steps to reproduce the behaviour

1. Open any demo where panning is allowed on a device that supports touch events
2. Pan an svg-element with two fingers

### Configuration

- svg-pan-zoom version: `The latest version from github`
- Browser(s): `all`
- Operating system(s): `all`

Feature Request
---

- Add an option to disable multitouch
- Default behaviour should not be affected. So standard multitouch is enabled but an option to disable it would be super.
- No, as the default behaviour is not affected

**Comment by bumbu** [comment]
Hi @KoenkookpotPlasmans, 

Sorry for a late reply. 

I saw your PR and it looks good. And I agree that we should not introduce breaking changes, thus using an option to enable/disable desired behaviour is good. But in this case it seems that current behaviour is a bug, and fixing it will add benefit to all existing users, so we don't even have to use the flag. We just have to fix the behaviour. 

There are some demos in the codebase on how to handle touch gestures. But they are based on simply disabling library's default behaviour and implement custom behaviour. So if anyone implemented custom behaviour using that method, they should not be affected by that change. 

So hence the question - do you know of any use case where we would want the current behaviour? And if not then I'd propose to simply fix this behaviour. What do you think?

**Comment by KoenkookpotPlasmans** [comment]
Hi @bumbu ,

I wasn't sure it would be considered a bug though the effect of using multiple gestures is quite 'annoying'.
I can't think of any use case where you would want this behaviour. I added the flag for enabling/disabling because I might have overlooked a use case for multiple gestures. But as we're both unable to find one, it might be better to simply not allow multiple gestures when panning. 

I will change the PR so that the flag is deleted and the bug is removed if that's ok with you.

**Comment by KoenkookpotPlasmans** [comment]
Ok, I changed the PR to have multitouch disabled at all times when panning.

**Comment by bumbu** [comment]
Hi @KoenkookpotPlasmans,

Thank you for your update. The PR looks good. I'm currently on holidays, but as soon as I'm back I'll take action on it.

**Comment by bumbu** [comment]
I was thinking about this issue and I'm not sure that `isMultiTouchEvent` is the right solution. Mainly because it assumes that `first changed touch is not the first registered touch` but from what I understand - often, first registered touch may be also the first changed touch. Although it should work correctly because the library uses only first `changedTouch` event, it adds distributed complexity. 

It seems that a much easier approach would be to simply always use first event (`evt.touches[0]`) and not first changed touch. That should solve the problem with jiggering, is very easy to understand and is exactly what you described in _expected behaviour_.

Also I don't see the need for an option as this is a bug and not a feature. 

What do you think @KoenkookpotPlasmans ?

**Comment by KoenkookpotPlasmans** [comment]
Hi @bumbu ,

You are correct that using the `evt.touches[0]` instead of the `changedTouch[0]` also solves the issue.
However, multi-touch will trigger multiple events for each 'touch' that changed. So moving with for instance three fingers will trigger 3 events (from what I've seen in tests). with each time a different changedTouch. If we use `evt.touches[0]`, the underlying code will still be executed 3 times, each time with the same touch/position.

The `isMultiTouchEvent` function will filter out any unnecessary events. So instead of three events triggering code, it will only allow the first touch to trigger further code. Less execution time seems better versus complexity (though in my opinion not that complex).

I thought I removed the option to enable/disable the event filtering from the pull request. No?

**Comment by bumbu** [comment]
Oh, you're right - the option got removed. I thought it's still present.

You're right that if we're going to use `evt.touches[0]` then when there are other touches changing their positions - the underlying code will execute in vain. But it's execution will stop inside of `this.viewport.setCTM(viewportCTM)` as that method checks if new viewport is any different from previous viewport. So the execution will stop not far away from where the `if (!Utils.isMultiTouchEvent(evt)){` is currently. 

Also I agree that the code in itself is not complex, but half of the logic is in `isMultiTouchEvent` (ignore events where there is no first touch in `changedTouch`) and second half is in `mouseAndTouchNormalize` (use only first `changedTouch` touch data) - and that makes it complex overall.

So I'd go with the easier solution - always using `evt.touches[0]`. @KoenkookpotPlasmans what do you say?

**Comment by KoenkookpotPlasmans** [comment]
Ah, yes. You check for any changes. 
Then your solution is indeed the best. I'll change the PR for this and let you know but I'll do it as soon as possible.

**Comment by KoenkookpotPlasmans** [comment]
Hi @bumbu,

I changed the PR to use `evt.touches[0]` and tested it on some devices and different browsers.
Can you let me know if this solution is the one we discussed?

Cheers,
Koen.

**Comment by bumbu** [comment]
Hi @KoenkookpotPlasmans,

Yes, the code looks good. I'm going to test it, remove dist files and merge your PR. Hopefully that will be today!

**Comment by bumbu** [comment]
Hi @KoenkookpotPlasmans,

You're changes are now in master. You can see that I closed that PR as I had so separate source code changes and build into separate commits.
I also published a new version on npm. 

Thank you for all your time and effort!

**Comment by KoenkookpotPlasmans** [comment]
Hi @bumbu ,

First of all thanks for making this awesome library and second thanks for helping me fix the bug!
I really appreciate it. Keep up the good work!

Cheers,
Koen.
