### ISSUE TITLE
Multiple svg file s

### ISSUE THREAD

**Issue by swissscheese** [ariutta/svg-pan-zoom#256]
Hello,

Is it possible to add multiple svg files overlay? The zoom function should be done on all the images. The goal is to build a map with dynamic content.

Thanks a lot for your help

Christophe

**Comment by ariutta** [comment]
Hi @swissscheese, can you re-ask this on stackoverflow? Thanks.

**Comment by bumbu** [comment]
I posted [an answer on stackoverflow](https://stackoverflow.com/a/45211879/1194327)
