### ISSUE TITLE
Refresh viewport

### ISSUE THREAD

**Issue by Jelledb** [ariutta/svg-pan-zoom#258]
Is it possible to reset the viewport? When I add an SVG element using snapsvg, the newly added SVG element is not added within the viewport.

**Comment by Jelledb** [comment]
Solved it using the following piece of code, but there might be a better way.

    function refreshViewport() {
        var allChildren = document.getElementById('layerForeground').children;
        var viewport = document.getElementsByClassName('svg-pan-zoom_viewport')[0];

        // As the children are appended, do a reverse for loop until the viewport is found.
        for (var i = allChildren.length - 1; i >= 0; i--) {
            var c = allChildren[i];
            if (c.classList.contains('svg-pan-zoom_viewport')) {
                break;
            }
            viewport.append(c);
        }
    }

**Comment by bumbu** [comment]
Hi @Jelledb,

As you mentioned there is no way to reset the viewport. 
The best solution would be adding those elements directly into the viewport group (if that's possible with snapsvg).
