### ISSUE TITLE
Preserve element size when zoom

### ISSUE THREAD

**Issue by SvilenStoianov** [ariutta/svg-pan-zoom#259]
Is there a way to preserve a element size when zoom? I try to do a SVG map with markers like circles. But when I zoom, circles also zoom and getting bigger. I've found that with vector effect I can fix stroke width. Also found this solution:

https://stackoverflow.com/questions/10694347/scale-independent-elements

But it seems that i can't figure out how to use it correctly with svg-pan-zoom library.

Also I wonder - is it possible to drag and drop some element? Mean just that element to be excluded from pan functionality? I was try some approach like jQuery draggable but with no luck.

Thank you in advance and excuse me if I type my question wrong.

**Comment by bumbu** [comment]
Please see #150

**Comment by SvilenStoianov** [comment]
@bumbu - thank you for your support. 
You point me to use custom viewport option, which make pan-zoom ability only to one SVG element. In fact I was asked for ability to remove only zoom option, pan functions must be preserved at all. 

In my case, i use SVG to draw a geo reffered map. Using custom viewport cause that this element lose him geo reference, because he stay outside of svg-pan transformation.

**Comment by bumbu** [comment]
I see what you mean. 

There is no option that would automatically do what you want. You'll have to register a zoom callback, and manually change the size of each circle when a zoom would occur. 

Also we keep github issues for issues, that's why I closed this issue. For questions please use [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help).

**Comment by SvilenStoianov** [comment]
Thank you. I was already place my question there. Also - try to deal it myself.... but i'm not so good as support team here.

Thank you again

**Comment by Godefroy** [comment]
A solution that works for me is to set a CSS variables for zoom scale and to use it in CSS.

Set the CSS variable when zoom changes:
```js
.on('zoom', (event) => {
  this.svg.style.setProperty('--zoom-scale', event.transform.k.toString())
})
```

Use zoom scale in CSS, for example to set a constant stroke width = 4:
```css
stroke-width: calc(4 / var(--zoom-scale));
````

**Comment by alitan** [comment]
> A solution that works for me is to set a CSS variables for zoom scale and to use it in CSS.
> 
> Set the CSS variable when zoom changes:
> 
> ```js
> .on('zoom', (event) => {
>   this.svg.style.setProperty('--zoom-scale', event.transform.k.toString())
> })
> ```
> 
> Use zoom scale in CSS, for example to set a constant stroke width = 4:
> 
> ```css
> stroke-width: calc(4 / var(--zoom-scale));
> ```

Do you mind telling us which library you are using?
Where can i get evet.transform.k ???
Are you using what we are using?

**Comment by Godefroy** [comment]
@alitan It's the official d3 zoom
https://d3js.org/d3-zoom#_zoom
