### ISSUE TITLE
Even the demo is unusable

### ISSUE THREAD

**Issue by gigawert** [ariutta/svg-pan-zoom#260]
Bug report
---

### Expected behaviour
The embedded svg demonstration shows up with zoom and pan ability along with controls.
### Actual behaviour
Embedded svg demonstration AND using my own SVG does not work, even when opening it immediately after downloading this repo. It shows up but does not have any interactivity. However the inline svg demo does work.

### Steps to reproduce the behaviour

1. Download repository
2. Open demo/embed.html and see that it doesn't work

### Configuration

- svg-pan-zoom version: `` the latest one
- Browser(s): `` Chrome v.60
- Operating system(s): `` Windows 10
- A relevant example URL: see above

**Comment by bumbu** [comment]
Hi @gigawert ,

Can you please try [online demoes](https://github.com/ariutta/svg-pan-zoom#demos)?

I just checked `demo/embed.html` locally (although on OSX) and it works just fine. But I open it locally using an Apache server. 

Most probably there's a problem with paths or frame permisions. If you try opening an HTML file directly from files system, it may not work. I tried doing that and I got that error in console:
![image](https://user-images.githubusercontent.com/171178/29735671-9252812a-89f2-11e7-818e-b947027087f5.png).

I suppose that's the case. If that the case, and you still want to run the demo locally then some options would be:

* Set up a [local dev server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Set_up_a_basic_working_environment)
* Run `node server.js` that will allow you opening the demo at `http://localhost:3001`. You have to do `npm install` first in project directory

**Comment by bumbu** [comment]
Closing it as there is no reply from the author.
