### ISSUE TITLE
Infinite pan on touch devices

### ISSUE THREAD

**Issue by Venegrad** [ariutta/svg-pan-zoom#261]
Hi all, have a some problem. If viewport is full screen, on mobile devices users cant scroll page, beacause drag in infinite. In desktop, i can fix maxzoom and minzoom onscroll. But how to fix maxdrag? Or how i can using drag on two fingers? If im trying limin with beforepan, page cant drag on maximum zoom ( Sorry for perfect english (

**Comment by bumbu** [comment]
Hi @Venegrad, 

For support or questions it's better to use [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help) as we use GitHub issues for bugs and features. 

Few possible solutions are:
* Provide the `onPan` callback, and when the user pans too far - scroll the page using JavaScript. You'll need to do the calculations for "pans too far" by yourself, but I imagine it should be based on pan, zoom and viewport values
* Add a button on top of SVG (I mean visually it should be over SVG) and use it to toggle pan functionality
* Add hammer.js library and set up your own [custom events](http://ariutta.github.io/svg-pan-zoom/demo/mobile.html). As you said you may want to enable SVG pan when panning with 2 fingers, and skipping it if it's just one finger
