### ISSUE TITLE
Disable Zoom Out OR Hide minus icon on Default SVG size

### ISSUE THREAD

**Issue by calsmith348** [ariutta/svg-pan-zoom#266]
Hi Ariutta,

I am using your svg-pan-zoom plugin but I need to hide minus icon on default size of SVG. When we click on plus icon (for zoom in) only then minus icon will show otherwise it will be hidden

Is their any default variable to set it OR I need to do some modification in script?

**Comment by bumbu** [comment]
Hi @calsmith348 , 
As this is a support question you have more chances to get better responses on StackOverflow as described [here](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help).

As a quick answer - no, there is no such functionality out of the box.
You can disable or enable default controls completely. Or you can go and build your own controls as in [this example](http://ariutta.github.io/svg-pan-zoom/demo/custom-controls.html) - then you can control when to show/hide any button.
