### ISSUE TITLE
How to prevent image from moving out of the viewport

### ISSUE THREAD

**Issue by hauleth** [ariutta/svg-pan-zoom#271]
I need to keep image always in viewport. So there are 2 actions required:

- on pan, prevent action if any part of default image will get out of the viewport
- on zoom, I should also centre around image centre

It doesn't need to be part of the library, but at least example how to achieve something like this would be nice.

**Comment by bumbu** [comment]
Hi @hauleth 
Such a question is better to be asked on StackOverflow, as issues are more for bugs and features. 

To try to answer your question look at [limit pan example](http://ariutta.github.io/svg-pan-zoom/demo/limit-pan.html). For the zoom you can do something similar by using `beforeZoom` event. Take into account that when you zoom - both pan and zoom are triggered. 

Hope that helps.
