### ISSUE TITLE
Changing position of control elements from lower right to uper left corner

### ISSUE THREAD

**Issue by BSchmidt1** [ariutta/svg-pan-zoom#273]
Hi thanks for the awesome library,

I have seen to the custom control demo, but I was wondering whether there is an easy way to change the position of the original controls (in my case from the lower right to the upper left corner). It's helpful when there is free space in an area of the image. Adding the functionality to the code might break something, but if there was a simple part of the code I (and anyone who also needs this and reads this issue) could change to switch the position, that would probably be enough for most people.

Thanks in advance :)

**Comment by bumbu** [comment]
Hi, 

No, there is no way to configure that. 
The recommended way is to use custom controls (the one you mentioned) and position them as you need.
Or you could change the source code of the library and alter the controls, but it means you'll have to do it for every update (so I don't recommend that).
