### ISSUE TITLE
Image in SVG only Display in Desktop Browser and Android Browser Not in iPhone Browser

### ISSUE THREAD

**Issue by MarkSky** [ariutta/svg-pan-zoom#274]
Bug report
---

### Expected behaviour
I would like to let the svg display in any device.
```
<svg id="svg-id" class="svg-map" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <g>
        <image xlink:href="../images/map.jpg" x="0" y="0" />
    </g>
    <g>
        <circle class="btns" cx="1858" cy="1272" r="15" />
    </g>    
</svg>

```
### Actual behaviour
The image in svg could display in desktop browser and any browser in Android.
But it doesn't display in any browsers in iPhone.
If it can't display image in iPhone?

### Configuration

- svg-pan-zoom version: `3.5.2`
- Browser(s): `Safari, Chrome, Firefox, Edge`
- Operating system(s): `iOS 11.2.1`
- A relevant example URL:

**Comment by bumbu** [comment]
Hi, 

It seems that it isn't a library issue, but rather that specific browser issue.
Can you please test if that SVG renders the image in iPhone browsers without using this library. If it does then we'll reopen the issue.
