### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by ptitdje45** [ariutta/svg-pan-zoom#275]
Hello,

I can't manage to install svPanZoom in angular 4.

Is there any way to add it easely as a module ?

Thanks

Jérémy

**Comment by bumbu** [comment]
Hi @ptitdje45, 

We didn't test it with Angular, but you could try this wrapper [Promact/angular-svg-pan-zoom](https://github.com/Promact/angular-svg-pan-zoom). 
Would be interesting if it works. If you manage to make it work, please post here so that others would be able to use it too.

**Comment by bpons** [comment]
I managed to make it work on a dynamically loaded svg, simply by calling it from ngAfterViewChecked()

```
import * as SvgPanZoom from 'svg-pan-zoom';
....
  svg: SafeHtml;
  svgPanZoom: SvgPanZoom.Instance = null;
  needsToInitSvgPanZoom = false;
.....
  ngAfterViewChecked() {
    if (this.needsToInitSvgPanZoom) {
      if (this.svgPanZoom) {
        this.svgPanZoom.destroy();
      }
      this.svgPanZoom = svgPanZoom('#svgDiv svg:first-child', {
        minZoom: 0.1,
        maxZoom: 10,
      });
      this.needsToInitSvgPanZoom = false;
    }
  }
....
    this.http.get(url, {headers: new HttpHeaders({'Accept': '*/*' }), responseType: 'text'})
      .subscribe(
        (response) => {
          // console.log('DONE : ', response);
          this.svg = this.sanitizer.bypassSecurityTrustHtml(response);
          this.needsToInitPanZoomSvg = true;

```
