### ISSUE TITLE
How to limit Zoom of svg till the element is in view?

### ISSUE THREAD

**Issue by tarunagrawal1990** [ariutta/svg-pan-zoom#276]
I want to zoom a svg image in such a way that the element which I want to zoom should always present in the view. If element is going beyond the view limit then svg should not zoom further.

Please suggest any solution. Thanks in advance.

**Comment by bumbu** [comment]
Hi @tarunagrawal1990 
Such a question is better to be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/svgpanzoom), as issues are more for bugs and features. 

To try to answer your question look at [limit pan example](http://ariutta.github.io/svg-pan-zoom/demo/limit-pan.html). For the zoom you can do something similar by using `beforeZoom` event. Take into account that when you zoom - both pan and zoom are triggered. 

Hope that helps.
