### ISSUE TITLE
Pan-Zoom cuts map size

### ISSUE THREAD

**Issue by hirschferkel** [ariutta/svg-pan-zoom#281]
Hi there!
I tried to run svg-pan-zoom, and implemented it just into a world-map- project. Unfortunately the library now cuts my svg-map and I do not kow why. There is no error listet in console and the script is running as one can move and scale the map. But it should fill full siize of the browserwindow and it is cut vertically at maybe 20%.
Seems lika a bug too me. Do you know what can be done to make it run properly?

Here is an example of the map:
#link
Best

**Comment by bumbu** [comment]
Hi @hirschferkel, 

Because the library removes the `viewBox` property from the SVG - you have to specify a height to it (in your case you should add it to `object`). 

Let me know if that helps.

**Comment by hirschferkel** [comment]
Hi bumbu,

actually this does not really help. The navigation bars will not be visible and the svg used to fit to the iframe (object width="100%"). After adding height to the object it will not work any more. I updated the map as you mentioned:
[Map-Link](http://ixtract.de/Karten/worldmap_Merics_ixtract_CO_zoom.html)
If you scale your browser window differently and reload the page, the svg does not fit to the 100% width anymore.
But it should work like this (the svg-map without pan-zoom):
Map without(http://ixtract.de/Karten/worldmap_Merics_ixtract_CO.html)

best, hirschferkel

**Comment by bumbu** [comment]
It does work. Your object width is 100% and height is 70%. From what I see - it perfectly does that job. 

If you want to simulate the behaviour that you had before - then a solution is to set object height with JavaScript (you should do it before initialising the library). On window resize after updating object's height - you'll have to call `svgPanZoom.resize()` and `svgPanZoom.fit()` (fit is necessary if you want it to take entire space, if not - you'll have to compute zoom level so that the map takes 100% width).

**Comment by hirschferkel** [comment]
Maybe I'm wrong, but that's what i see with pan-zoom:
![bildschirmfoto 2018-01-28 um 23 41 58](https://user-images.githubusercontent.com/16016422/35488204-01b1b1aa-0485-11e8-956b-93719fdebdb9.png)
And that's how it should look like...
![bildschirmfoto 2018-01-28 um 23 42 04](https://user-images.githubusercontent.com/16016422/35488207-0ca9e5e6-0485-11e8-99f2-6e5e11ad038a.png)

quite different, isn't it?

**Comment by bumbu** [comment]
Check this section of FAQ
https://github.com/ariutta/svg-pan-zoom#how-to-limit-zoomingpanning

**Comment by hirschferkel** [comment]
Hi bumbu,

that's not what i mean. Try to describe it differently: If you minimized the svg so it does not intersect any border of the pan-viwe-area, is it possible to limit the movement within the pan-area so the minimized svg will not escape the pan-view? 

Or when you maximize the scg so it is much bigger than the pan-view, is it possible to force the right border of the svg to not cross the right border of the pan-view?

I saw only examples where you can move the svg like you want without any limitation. Not speaking about the zoom, about the movement of the svg.

**Comment by bumbu** [comment]
From what I understand - limit pan example is what you describe. It's just in that example the limit is not at the border of the image, but more inwards.
