### ISSUE TITLE
enable dragging or "panEnabled" from blank svg

### ISSUE THREAD

**Issue by tzookb** [ariutta/svg-pan-zoom#283]
I noticed you have the possibility of dragging or not with: `panEnabled`

but I want to provide dragging, but only if it gets dragged after a click on an empty spot.

I mean I have the blank svg, and on it I have `rects`

- so when he clicks on "no" rect and drags, the view should move
- when he clock on a rect and drag, the view should stay in place

Any ideas on that?

![drag](https://user-images.githubusercontent.com/3749973/36340248-cec7d442-13e1-11e8-8275-ac87bc1dfa81.png)

**Comment by bumbu** [comment]
You can disable panning for specific events through `onPan` callback, but you'll have to detect those events by yourself. Alternatively you can overwrite any event and have your own implementation. 

https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help
