### ISSUE TITLE
absolute zoom not possible,

### ISSUE THREAD

**Issue by wentin** [ariutta/svg-pan-zoom#286]
https://github.com/ariutta/svg-pan-zoom/blob/a26e79582adb7bdecbb6a77a4aeaafedc77ea9f0/src/svg-pan-zoom.js#L702

issues:
1. This makes zoom(num, false), the `false` not functioning
2. code semantic issue, if absolute is true, it means relative zoom, that is counter intuitive.

**Comment by bumbu** [comment]
I suppose you found out that there is also `zoomBy` that passes `false` as second argument. 
Leaving it here in case someone else gets into the same issue
https://github.com/ariutta/svg-pan-zoom/blob/a26e79582adb7bdecbb6a77a4aeaafedc77ea9f0/src/svg-pan-zoom.js#L702-L703
