### ISSUE TITLE
zoomAtPointBy not working

### ISSUE THREAD

**Issue by dzza** [ariutta/svg-pan-zoom#290]
Hello,

panBy, zoomBy, zoom and friends all work, but zoomAtPoint and zoomAtPointBy don't. Calling them does nothing.

Any ideas what are possible reasons for this? Not sure where to start digging

**Comment by bumbu** [comment]
Hi, 

Please provide a reproducible example as described [here](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues). Otherwise it's really hard to help.

**Comment by bumbu** [comment]
Closing as not further details provided
