### ISSUE TITLE
I'm using svg object inside the iframe but pan zoom is not working only in iphone

### ISSUE THREAD

**Issue by upalbyani** [ariutta/svg-pan-zoom#292]
Hi there!

Thanks for submitting an issue to svg-pan-zoom.

To help us help you better, please do the following before submitting an issue:

1. Review:
  * Available documentation https://github.com/ariutta/svg-pan-zoom/blob/master/README.md
  * Common Issues & FAQ https://github.com/ariutta/svg-pan-zoom#common-issues--faq
  * Existing examples https://github.com/ariutta/svg-pan-zoom#demos
1. Check if the same bug/feature request [wasn't previously reported](https://github.com/ariutta/svg-pan-zoom/issues?q=is%3Aissue%20)
1. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/svgpanzoom).
1. Fill in the information that corresponds to your type of issue below
1. If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/bumbu/167usffr/).
1. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)

Bug report
---

### Expected behaviour
_your text here_

### Actual behaviour
_your text here_

### Steps to reproduce the behaviour

1.
2.

### Configuration

- svg-pan-zoom version: ``
- Browser(s): ``
- Operating system(s): ``
- A relevant example URL:

Feature Request
---

- Feature description
- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by bumbu** [comment]
> Delete this intro and any unrelated text 😄 (if you do not we'll assume you haven't read these instructions and automatically close the issue)
