### ISSUE TITLE
Can't handle click events.

### ISSUE THREAD

**Issue by balferreira** [ariutta/svg-pan-zoom#293]
I there.

I'm trying to use your amazing plugin but I'm facing some problems.
On my svg file I've something like this:

> < a id="SVG_TEST" data-toggle="modal" data-target="#myModal" class="myModal" style="cursor: pointer;">
> 
>     <path d="M485.63 365.7L513.83 344.73" fill="none" stroke="RGB(137,137,137)" stroke-width="0.5"/>
> 
> < /a>

I'm trying to open a modal or at least check if the user click on that specific part of the svg file with this:

>    $(document).on("click", ".myModal", function ()
>     {
>         console.log("AKI...");
>     });
>     
>     $("#SVG_TEST").on("click",function()
>     {
>         console.log("...AKI...");
>     }); 

But if I "open" the svg with your framework, I'm not able to handle the click event.
If I use the svg without your framework, I can handle the click event and everything works fine.

Can you tell me what I've to do in order to be able to handle the click events?

Great work.
Thanks.

**Comment by balferreira** [comment]
Hi there.
I've another information about this issue. If I include the svg like this way:
`<object id="demo-tiger" type="image/svg+xml" data="/global_/images/envato/Tux.svg" style="width: 100%; height: 700px; border:1px solid black; ">Your browser does not support SVG</object>`

or this way

`<embed id="demo-tiger" type="image/svg+xml" style="width: 500px; height: 500px; border:1px solid black; " src="/global_/images/envato/Tux.svg" />`

The click event not working...

But if I copy the content of Tux.svg and add the **id="demo-tiger"** to **svg tag**.
The click event works great.. I guess the problem have something related to the way I include the svg file... Any idea of way this is happening?

Kind regards

**Comment by bumbu** [comment]
Set the `preventMouseEventsDefault: false` when initialising the library

**Comment by sixingxu** [comment]
Hi, I'm encountering the same problem... click event doesn't seem to work if the svg is embedded, even with preventMouseEventDefault set to false...

**Comment by bumbu** [comment]
Hi @sixingxu, can you please provide a [reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues)?

**Comment by orangeSi** [comment]
I meet the silimar problem, and resolved  by ``` addEventListener('click', function(){ })``` instead of ``` onclick=funciton(){ }```

**Comment by sancelot** [comment]
Hi
I have similar problem . I noticed that the first click was preparing pan mode. To allow the click to work I have to move à little bit my mouse and click again. This click Will be taken into account
