### ISSUE TITLE
R svgPanZoom within shinyApp display different in the Web and Rstudio

### ISSUE THREAD

**Issue by Jiajin626** [ariutta/svg-pan-zoom#295]
Firstly,Thanks for your great job.
Here is my problem:
I draw a picture using R with packages svgPanZoom,svglite,ggplot2 and shiny. However, it can display correctly on Rstudio but not on Web. Are there any options to solve it? Please run the following code for detail.
`library(shiny)
library(svglite)
library(svgPanZoom)
library(ggplot2)

data<-data.frame(x=1:50,y=1:50)
x_position<-1:50
y_position<-1:50
ui <- pageWithSidebar(
headerPanel(""),
sidebarPanel(),
mainPanel(

column(width=12,svgPanZoomOutput(outputId = "main_plot",width=600,height=450))

))

server = shinyServer(function(input, output) {
output$main_plot <- renderSvgPanZoom({
p <- ggplot(data, aes(x = x, y = y)) + geom_point()

svgPanZoom(
  svglite:::inlineSVG(show(p))
  , controlIconsEnabled = T)

})
})

shinyApp(ui,server)`

Detail in:
https://stackoverflow.com/questions/50083003/r-svgpanzoom-within-shinyapp-display-different-in-the-web-and-rstudio

**Comment by bumbu** [comment]
Hi, please post this issue in the [R repo](https://github.com/timelyportfolio/svgPanZoom), this repo is for JavaScript version.
