### ISSUE TITLE
 Resize two SVGs with window.onload and using ajax

### ISSUE THREAD

**Issue by DaveSimmons1234** [ariutta/svg-pan-zoom#296]
Hi there,

I'm trying to get 2 inline svgs to resize together (as they overlay each other) - as well as having "Two SVGs with synchronized zooming and panning" - is this possible? Also is it possible not to use window.onload for these example - so that I can have them working with AJAX? 

Any help would be much appreciated.

Thank you 
Dan

**Comment by bumbu** [comment]
Hi, 

> I'm trying to get 2 inline svgs to resize together (as they overlay each other) - as well as having "Two SVGs with synchronized zooming and panning" - is this possible? 

Yes

> Also is it possible not to use window.onload for these example - so that I can have them working with AJAX?

Yes. Check demos, some of them show dynamic loading. 

https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help
