### ISSUE TITLE
how to delete issue?

### ISSUE THREAD

**Issue by chisholmd** [ariutta/svg-pan-zoom#298]
I am dynamically adding SVG elements to my illustration.  But they don't zoom with the rest of the drawing.  What am I missing?

// svg-pan-zoom v3.5.2
Chrome

**Comment by chisholmd** [comment]
Sorted it out

**Comment by ariutta** [comment]
Glad it's working now. If you've made a Polymer wrapper, it'd be cool to list it as a wrapper [here](https://github.com/ariutta/svg-pan-zoom#related-work). Pull request?
