### ISSUE TITLE
Uncaught DOMException: Failed to execute 'inverse' on 'SVGMatrix': The matrix is not invertible.

### ISSUE THREAD

**Issue by yangdan8** [ariutta/svg-pan-zoom#308]
这个bug比较难重现,我只能写个控制台报错内容,然后将错误的代码位置上传给你
This bug is hard to reproduce. I can only write a console to report the wrong content and upload the wrong code to you.
![qq 20180807090526](https://user-images.githubusercontent.com/16515026/43748373-cb3af874-9a21-11e8-9573-e75290e29a83.jpg)
![qq 20180807090601](https://user-images.githubusercontent.com/16515026/43748375-ceba2c7c-9a21-11e8-85b7-988c3fa4075e.jpg)

**Comment by bumbu** [comment]
Closing as no details provided.

**Comment by hermanbanken** [comment]
I'm seeing this as well. Either `reset`, or `destroy`.
<img width="1281" alt="Screenshot 2019-10-27 at 21 11 56" src="https://user-images.githubusercontent.com/791189/67640977-6ddb9700-f8fe-11e9-90c9-cb60d3123b75.png">

I'm using Chrome 77.

**Comment by hermanbanken** [comment]
The SVG is definitely not unmounted.

**Comment by hermanbanken** [comment]
Nevermind, I found that simply having multiple instances of SVGPanZoom on the same page causes this issue too! Fixed that by only rendering one at the same time.

**Comment by the-gc** [comment]
I also encountered this problem, I now need to render multiple instances at the same time, how can I deal with it。

**Comment by HammadManzoor** [comment]
Faced the same issue. The problem occurs when you try to use reset when the container for the svg is not visible on the viewport. I fixed it by checking for this before performing reset.

` const divElement = this.el.nativeElement.querySelector(
      '#myContainer'
    );
    if (divElement) {
      const viewportHeight = window.innerHeight;
      const divOffset = divElement.getBoundingClientRect().top;
      // Check if the div is in the viewport
      if (divOffset < viewportHeight) {
              this.svgPanZoom.resize();
              this.svgPanZoom.reset();
          }
     }
`
