### ISSUE TITLE
controlIcons position

### ISSUE THREAD

**Issue by donniekerr** [ariutta/svg-pan-zoom#312]
Can I change the position of the controls from bottom right corner to top left corner? 

Thanks,
Donnie

**Comment by bumbu** [comment]
You can implement your own custom controls like in [this demo](http://ariutta.github.io/svg-pan-zoom/demo/custom-controls.html). 
Otherwise there are no options to control icons position. 
Alternatively you can edit the source code.

**Comment by lancedouglas1** [comment]
> You can implement your own custom controls like in [this demo](http://ariutta.github.io/svg-pan-zoom/demo/custom-controls.html). Otherwise there are no options to control icons position. Alternatively you can edit the source code.

The link is broken.

This works for me:

```
            // reposition the controls
            const controls = document.querySelector('g[id="svg-pan-zoom-controls"]');
            //get height and width of svg
            const svgHeight = svg.getBoundingClientRect().height;
            const svgWidth = svg.getBoundingClientRect().width;
            //set the controls to be 15% from the top of the svg and 100px from the right
            controls.setAttribute('transform', 'translate(' + (svgWidth - 100) + ', ' + (svgHeight * 0.15) + ')');
```

I also wrap this in a function that fires on window resize.
