### ISSUE TITLE
Element does not follow mouse pointer properly (mousemove)

### ISSUE THREAD

**Issue by dgroh** [ariutta/svg-pan-zoom#313]
Bug report
---

### Expected behaviour
I have two SVGs, one **with** `svg-pan-zoom` and the other **without** it.

Both SVGs have elements and when I click one of those elements, I can move it around making it follow the mouse pointer.

### Actual behaviour

The selected element from the SVG **with** `svg-pan-zoom` does not follow the mouse pointer properly, there is a big offset gap.

### Steps to reproduce the behaviour

1. Create an SVG with a `circle`
2. Implement a mouse move event to this circle and make it follow the mouse pointer

I used the following function to get the mouse coordinates from the SVG:

```
  getCursorPoint(event) {
    const point = this.SVGMap.createSVGPoint();
    point.x = event.clientX;
    point.y = event.clientY;

    const CTM = this.SVGMap.getScreenCTM();

    return point.matrixTransform(CTM.inverse());
  }
```

### Configuration

- svg-pan-zoom version: `^3.5.3`
- Browser(s): `all browsers`
- Operating system(s): `Windows 10`
- A relevant example URL:

**Comment by bumbu** [comment]
It's hard to understand if this is an actual issue or not without a reproducible example. 
The only thing I could recommend is to try and get internal CTM by subscribing to `onUpdatedCTM` and caching that value. Or at least compare if `this.SVGMap.getScreenCTM()` gives you the same value as `onUpdatedCTM`.
Another idea is to check if matrixTranform works correctly when the viewport is panned (aka top left corner is not in top left position of the SVG).

**Comment by dgroh** [comment]
Very legit and makes sense. I'll give it a try with `onUpdateCTM`.

 I'll try in the course of the day to create a reproducible example for sure. Thank you very much.

BTW, why do you mean with the matrixTransform?

**Comment by dgroh** [comment]
Ok, getting the new CTM from the callback worked for me! 

Much appreciated the support.

So closing the issue!
