### ISSUE TITLE
Inverting pan direction, when displaying svg with transform: rotate(180deg)

### ISSUE THREAD

**Issue by KaloyanDimitrov** [ariutta/svg-pan-zoom#318]
I am displaying some svgs with a transform: rotate(180 deg) attribute. When such svgs are being display the panning is inverted, eg. mouse drag to the left moves the element to the right.

I am working in the beforePan() callback and I thought that the solution will be simple like: 

`deltaX = newPan.x - oldPan.x;`
`deltaY = newPan.y - oldPan.y;`

`newPan.x -= deltaX * 2;`
`newPan.y -= deltaY * 2;`

This inverts the panning, but the element moves at break-neck speeds, from one edge to the other. I started trying to use magic numbers and got a somewhat decent behavior but it is still not the same as the non-inverted movement.  I think that my lack of understanding of the oldPan and newPan is the root of my issue, so if someone could shed some light on it, that would be appreciated.
Any idea for how to achieve the exact same smooth movement as the original? My somewhat working solution is something like this:

`newPan.x -= deltaX;`
`newPan.y -= deltaY;`

`newPan.x -= deltaX / 25;`
`newPan.y -= deltaY / 25;`

**Comment by KaloyanDimitrov** [comment]
This is what I mean. 

https://jsfiddle.net/cqu0rw8h/8/

**Comment by KaloyanDimitrov** [comment]
I solved my issue. Just did the rotation on each child element of the svg, instead of on the container svg. No more inverting of the pan direction needed. =)

**Comment by bumbu** [comment]
Happy that it worked, I'll close the issue then.
