### ISSUE TITLE
Customize drag on to button click 

### ISSUE THREAD

**Issue by shyammbusa** [ariutta/svg-pan-zoom#321]
Hi , 

If I need to Override the Drag from mouse to Button click in SVG PAN Zoom. How will I do that. That is I have 4 buttons like forward, backward , left and right. On clicking the button, my SVG should move or drag forward ,backward ,left , right. Same time Mouse drag will work as default drag and zoom present in SVG pan zoom js

**Comment by bumbu** [comment]
Hey @shyammbusa 

If I understand your question correctly then you want to add custom controls (there's a demo) and use `pan` and `panBy` methods that the library exposes. 

But for the future please use [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help) for questions like this of for more details.
