### ISSUE TITLE
svg-pan-zoom/demo/object.html issue with Chrome

### ISSUE THREAD

**Issue by orangeSi** [ariutta/svg-pan-zoom#326]
Bug report
---
```
git clone  https://github.com/ariutta/svg-pan-zoom.git
```
I just git clone as that, and  opened svg-pan-zoom/demo/object.html with my chrome 71.0.3578.98(64) in Window7 computer for test, then get this error:
```
svg-pan-zoom.js:1714 Uncaught TypeError: Cannot read property 'documentElement' of null
    at Object.getSvg (svg-pan-zoom.js:1714)
    at svgPanZoom (svg-pan-zoom.js:1241)
    at window.onload (object.html:15)
```
I just download and not change the code of object.html.
but object.html work with IE.
now embed also not work with chrome, but inline work well with chrome.

### Configuration

- svg-pan-zoom version:  git clone  just now
- Browser(s):  chrome 71.0.3578.98(64) 
- Operating system(s):  Window7
- A relevant example URL: svg-pan-zoom/demo/object.html  in my disk

**Comment by bumbu** [comment]
Most probably this is an issue with how local files are loaded in the browser. 
If you open [online demo](http://ariutta.github.io/svg-pan-zoom/demo/object.html) then it's loading fine.
Also locally you can try running the server in the folder `node server.js` and the opening http://localhost:3001/demo/object.html to see that is works.

**Comment by orangeSi** [comment]
object.html  works when open it with server mode, thanks !

**Comment by ankostis** [comment]
(sorry to revive this, but could not find any solution, including dupe #364)
Any idea how we can accomplish pan+zoom locally with <object> & separate svg file, without a erver?

**Comment by orangeSi** [comment]
I gave up with separate svg file, and use in-line which works without s server,
example:   https://github.com/orangeSi/ClustersPloter/blob/master/example/out1.html

Maybe you can try firstly load the content of separate svg file, then assign the content to innerHTML of a <div>, so  the div have a child of svg. My above example  used div as parent of svg.

**Comment by michtoen** [comment]
I saw a bug report about local files poiting to this, so i assume its the same.

Modern Browsers updated their CORS rules. You can't load nested files using the file: protocol mixed with js or media anymore. The browser will refuse loading AND set any javascript file path to null. Thats part of the browser security.

Do not try to trick this out - its now a base part of the browser security. You can't give file: urls any CORS rule - the browser will always skip this.

You can try it out by starting chrome.exe without the web security like this:

"<YOUR_PATH_TO>\Chrome\Application\chrome.exe" --disable-web-security --disable-site-isolation-trials --disable-gpu --user-data-dir=C:/TEMP/chromeTemp

With that local html with js and media will execute again.

**Comment by orangeSi** [comment]
> I saw a bug report about local files poiting to this, so i assume its the same.
> 
> Modern Browsers updated their CORS rules. You can't load nested files using the file: protocol mixed with js or media anymore. The browser will refuse loading AND set any javascript file path to null. Thats part of the browser security.
> 
> Do not try to trick this out - its now a base part of the browser security. You can't give file: urls any CORS rule - the browser will always skip this.
> 
> You can try it out by starting chrome.exe without the web security like this:
> 
> "<YOUR_PATH_TO>\Chrome\Application\chrome.exe" --disable-web-security --disable-site-isolation-trials --disable-gpu --user-data-dir=C:/TEMP/chromeTemp
> 
> With that local html with js and media will execute again.

Is it possiable access the content of local file by HTML File Upload API then assign the content to innerHTML of a svg？

**Comment by FrankBuchholz** [comment]
> Is it possiable access the content of local file by HTML File Upload API then assign the content to innerHTML of a svg？

This is what I do in my [project](https://github.com/FrankBuchholz/EEP_convert_anl3_file): I read a local XML file via HTML File Upload API which contains graphical elements like line, arc, cubic, clothoid, helix as well as some texts. Then I convert them into svg path elements which I add to the svg DOM element.
