### ISSUE TITLE
Question : How can I use the viewport matrix 

### ISSUE THREAD

**Issue by sancelot** [ariutta/svg-pan-zoom#332]
I was using this function to retrieve the coordinates of a clicked point in the view.

// angular code.
 
```
 // Get point in global SVG space
  cursorPoint(evt:MouseEvent){
   this.pt.x = evt.clientX; 
   this.pt.y = evt.clientY;
   return this.pt.matrixTransform(
         this.mysvgRef.nativeElement.getScreenCTM().inverse());
}
```

 After integrating  svg-pan-zoom , the matrix is not the same one, and the retrieved coordinates are wrong.

How can I do ?

**Comment by SvilenStoianov** [comment]
library modify transform matrix when pan or zoom is applyed. You must use getScreenCTM().inverse() in order to see local coordinates. I use a follow helper function:

```
function svgPoint(element, x, y) {
  var pt = svg.createSVGPoint();
  pt.x = x;
  pt.y = y; 
  return pt.matrixTransform(element.getScreenCTM().inverse());
}

```
which can be used like:
```
<svg id="svg">
<g id="holder" class="svg-pan-zoom_viewport" >
.... //all svg elements
</g>
</svg>
<script>
var local=document.getElementById('holder'); //your local 
var svg=document.getElementById('svg'),
    	var x = evt.clientX,
	y = evt.clientY,
	svgP = svgPoint(svg, x, y),
	svgL = svgPoint(local, x, y);
</script>
```

Now in svgP and in svgL you will receive coordinates in screen space and  svg space

**Comment by sancelot** [comment]
Many Thanks !
