### ISSUE TITLE
Success story (EEP railroad track layout)

### ISSUE THREAD

**Issue by FrankBuchholz** [ariutta/svg-pan-zoom#354]
This is not an issue but a success story!

I use your library for my open-source [program](https://github.com/FrankBuchholz/EEP_convert_anl3_file) which shows railroad track layouts. (You create these railroad track layouts with [EEP](https://eepshopping.de/?lang=2).)

Below you see a panned and zoomed part of such a railroad track layout. The complete inline-svg could contain several thousand items!
![Railroad_tracks](https://user-images.githubusercontent.com/46897145/66026309-dbabc300-e4f8-11e9-8769-d862886e42dd.PNG)

**Comment by ethubert** [comment]
Great job! I'm also using it at work for a big project in an energy producing company where engineering charts also contain thousands of items and this library did the job better than the code I wrote myself, performance-wise especially. Big thanks to the developer!

**Comment by ariutta** [comment]
@FrankBuchholz and @ethubert, thanks for the kind words! And thanks to @aleofreddi for starting this library, to @bumbu for doing much of the work of extending and maintaining it, and to all the other contributors for their help.
