### ISSUE TITLE
Mobile support for pinch

### ISSUE THREAD

**Issue by bumbu** [ariutta/svg-pan-zoom#55]
We could add hammer.js to detect pinch event. Also when hammer.js would be available we could rely on its detection of pan and doubletap.

Related issue #47 
Implement when hammerjs/hammer.js#600 is closed

EDIT: there is a [demo solution](http://ariutta.github.io/svg-pan-zoom/demo/mobile.html) for that using hammer.js

**Comment by ravikumarjogu** [comment]
When I am using hammerjs with svg-pan-zoom to get pinch zoom interaction on mobiles. Its working fine but its reloading multiple times by crashing when I test on ipad. Any suggestions?

**Comment by nice7285** [comment]
you are my saver!!!
