### ISSUE TITLE
Pan, Zoom and Fullscreen controls

### ISSUE THREAD

**Issue by ariutta** [ariutta/svg-pan-zoom#7]
In the init method, we need the argument parameters specifying whether to include controls for panning, zooming and toggling fullscreen mode.

The controls would look something like the ones in [this diagram](http://wikipathways.github.io/pathvisiojs/test/compare.html?gpml=WP4), but they would be SVG elements that would be added to the target SVG if the user specified "true" for the arguments displayPanControl, displayZoomControl and displayFullScreenControl. The user would call something like this:

``` JS
svgPanZoom.init({
  'selector': '#my-svg', // optional selector. If left blank, svg-pan-zoom will look for the first SVG document in your HTML document.
  'panEnabled': true, // optional. values must be true or false. default is true.
  'displayPanControl': true, // optional. values must be true or false. default is true.
  'zoomEnabled': true, // optional. values must be true or false. default is true.
  'displayZoomControl': true, // optional. values must be true or false. default is true.
  'minZoom': 0.5, // optional. values must be scalar. default is 0.5.
  'maxZoom': 10, // optional. values must be scalar. default is 10.
  'zoomScaleSensitivity': 0.2, // optional. values must be scalar. default is 0.2.
  'displayFullScreenControl': true, // optional. values must be true or false. default is true.
  'dragEnabled': false, // optional. values must be true or false. default is false.
  'onZoom': function(scale) { ... }  // optional. Callback function when zoom changes.
});
```

This call would be handled by the [init method](https://github.com/ariutta/svg-pan-zoom/blob/master/svg-pan-zoom.js#L55). This feature would also require adding code to actually create and append the control elements to the SVG document.

The fullscreen control would work with the library [screenfull.js](https://github.com/sindresorhus/screenfull.js).

**Comment by frederikb** [comment]
Any chance of introducing the 'displayFullScreenControl' as described above? The screenfull.js library could be an optional dependency for those who do not require this functionality.

**Comment by bumbu** [comment]
Hey @frederikb 
Currently there're no plans for adding this functionality. From the looks of it - it doesn't have to be part of the core and can be added as an add-on that would use existing API. If you get to do it - feel free to post it here (or as a PR to demo folder) so that others can use it :)
