### ISSUE TITLE
Trouble implementing with RequireJS

### ISSUE THREAD

**Issue by oller** [ariutta/svg-pan-zoom#80]
Hi guys,

Forgive me if this is a silly question, but I'm having trouble implementing this library when loading it though RequireJS.  I'm not sure if it's a conflict with the browserify syntax?

As it stands, the only functions exposed/returned when 'requiring' svg-pan-zoom are:
https://github.com/ariutta/svg-pan-zoom/blob/master/dist/svg-pan-zoom.js#L166

```
Object {on: function, off: function}
off: function removeWheelListener(elem,callback,useCapture){...}
on: function addWheelListener( elem, callback, useCapture ) {...}
```

Am I doing something wrong, is there a way around this, or is this library not compatible with RequireJS without forking?

Many thanks in advance

**Comment by bumbu** [comment]
Hi, 

This is a really good question. Right now the library is not AMD compatible.
I have to think and to test. Or maybe someone found a workaround for that and will post it here.

But the idea is that it would be great to maintain library compatibility with browserify and in the same time to provide a way to use it with require.js. It is a tricky question.

**Comment by Chuckytuh** [comment]
Any news on this subject? Version 3.1.2 still acts the same way as the oller reported.

**Comment by bumbu** [comment]
I didn't have the time to look into this. But if anyone has done any progress with this - pull requests are welcome.

**Comment by oller** [comment]
:+1:
