### ISSUE TITLE
Can't select text within SVG image

### ISSUE THREAD

**Issue by arjSharma** [ariutta/svg-pan-zoom#81]
Hi, I'm having trouble selecting text within the SVG image when using this plugin. Has anyone else encountered this issue and know of any possible fix?

All text is unselectable, even when disabling pan and zoom functionality.

Thanks

**Comment by bumbu** [comment]
Is text unselectable even if you don't use svgpanzoom plugin?

**Comment by arjSharma** [comment]
I can select text when I don't use the svgpanzoom plugin. Is there a way to diable the plugin when pressing a key down, so I can select the text and then on keyup I can resume the plugin functionality? 

Also, what is the correct way to include the svg image in a html page? In the demo it says not to use window.open in production.

Thanks

**Comment by bumbu** [comment]
> I can select text when I don't use the svgpanzoom plugin. Is there a way to diable the plugin when pressing a key down, so I can select the text and then on keyup I can resume the plugin functionality? 

You can resume but this will not help.
The problem is that plugin listens for all mousedown, mousemove and mouseup events. All this events are prevented by using `preventDefault`. So it would require to refactor the library to allow default events processing when pan is disabled. 
If you don't need pan you can disable it and comment event preventing in:
* `SvgPanZoom.prototype.handleMouseDown`
* `SvgPanZoom.prototype.handleMouseUp`
* `SvgPanZoom.prototype.handleMouseMove`
This way text selection should work.

> Also, what is the correct way to include the svg image in a html page? In the demo it says not to use window.open in production.

As you saw demo explains why not to use `window.open`:
> `Don't use window.onLoad like this in production, because it can only listen to one function.`

So if you'll have another such function somewhere else then only one of them would work. If you use jQuery then you can do `$(function(){//your code here});`. Also I'm sure if `window.open` is cross-browser.

**Comment by arjSharma** [comment]
Hi Bumbu, thanks for your response.
I've noticed the preventDefault and have commented them out and disabled pan and I am able to select text. 

My problem is I require text selection, zoom and pan functionality. As the library will need to be amended to accommodate all of these features I have specified, are there any plans to include text selection in the next release of the library? 

Thanks

**Comment by bumbu** [comment]
> My problem is I require text selection, zoom and pan functionality. As the library will need to be amended to accommodate all of these features I have specified, are there any plans to include text selection in the next release of the library?

It is not trivial do to selection because the library should detect what's user intent (pan or selection). That's not easy, and different implementations may need different solutions (or none at all).

But it is possible to be done now. Take a look at `demo/mobile.html`. You would want to override default mouse events as:
```js
window.onload = function() {
  var eventsHandler;

  eventsHandler = {
    haltEventListeners: ['mousedown', 'mousemove', 'mouseup']

  , mouseDownHandler: function(ev){
      // Process mouse down event
    }
    
  , mouseMoveHandler: function(ev){
      // Process mouse move event
    }

  , init: function(options) {
      options.svgElement.addEventListener('mousedown', this.mouseDownHandler, false)
      options.svgElement.addEventListener('mousemove', this.mouseMoveHandler, false)
    }

  , destroy: function(options){
      options.svgElement.removeEventListener('mousedown', this.mouseDownHandler, false)
      options.svgElement.removeEventListener('mousemove', this.mouseMoveHandler, false)
    }
  }

  // Expose to window namespace for testing purposes
  window.panZoom = svgPanZoom('#mobile-svg', {
    zoomEnabled: true
  , controlIconsEnabled: true
  , fit: 1
  , center: 1
  , customEventsHandler: eventsHandler
  });
};
```

So you have to check in mousedown event if it happened over a text element or not. And then:
* if it was over a text element - do nothing
* if not then simulate panning via public API

You may choose to have a different way of checking what's the user intent.

**Comment by arjSharma** [comment]
Thanks Bambu, I've managed to get text selection working by overriding the default mouse events.

My only problem is panning isn't working at the moment, how do I similate panning via public API?

Thanks

**Comment by bumbu** [comment]
You access `pan` and `panBy` methods of svgpanzoom instance.
If to take the example that I provided earlier:
* First you store initial mouse position in `mouseDownHandler` 
* In each `mouseMoveHandler` you compute how much mouse moved and call `panZoom.panBy(x, y)` where x and y are your computed values.

**Comment by arjSharma** [comment]
Thanks for your message, I've managed to sort my issue.

**Comment by andrewboni** [comment]
Similar to this, I'd like to have two separate "modes" for my svg container:
1. `panEnabled` is `true` and `preventMouseEventsDefault()` is `true`
2. User toggles a button, which causes `panEnabled: false` and  `preventMouseEventsDefault: false`

I can use the API to toggle `panEnabled`, but didn't see how to toggle `preventMouseEventsDefault`- is this possible? If not, what's the best approach here?

**Comment by bumbu** [comment]
That is true that there is no API that would change the `preventMouseEventsDefault` value. 

What you can do is:
* Create a method to toggle this value. It can be similar to [enable/disableZoom](https://github.com/ariutta/svg-pan-zoom/blob/master/src%2Fsvg-pan-zoom.js#L644)
* Set `preventMouseEventsDefault: false`. Add a [custom handler](https://github.com/ariutta/svg-pan-zoom#custom-events-support) for mouse events you're interested in. And call `preventDefault` from your custom event handler when you need it. I'm not sure if this will work, but it should

**Comment by rangitha** [comment]
It would be beneficial in some scenarios to handle the `mouseleave` event in addition to the three handlers mentioned above. The behaviour of this handler would be similar to `mouseup`.

**Comment by ariutta** [comment]
@bumbu, could we do mouseleave the same way we do for the other events?

More generally, I came across a library that appears to address use cases
similar to the ones raised in this issue:

http://interactjs.io/api/

It might provide some ideas we could copy for svg-pan-zoom regarding how to
allow devs to specify their desired interaction types. This is probably
only relevant, however, if we ever implement that big "plug-ins allowed"
refactoring for a new major version.

**Comment by bumbu** [comment]
Hi @rangitha and @ariutta.

You can see in [svg-pan-zoom.js:131](https://github.com/ariutta/svg-pan-zoom/blob/master/src/svg-pan-zoom.js#L131) that the library does handle the `mouseleave` events. And as with other events - you can halt any of the events defined in there (inclusively `mouseleave`). 

@ariutta, can you please elaborate a bit more on which ideas exactly we could reuse from interactjs?
Is it the on/off methods, or draggable/gesturable methods that enable and configure specific interactions, or maybe it's something else?

**Comment by rangitha** [comment]
Hi @bumbu: 

Yes, I noticed. I was adding to your example on using `customEventsHandler`. My specific case was that panning and releasing the left mouse button outside of the SVG limits would continue the pan when the mouse re-enters the SVG again, even if none of the mouse buttons are pressed.

Not sure if that's case specific to me. However I easily fixed that by halting and handling `mouseleave`.

**Comment by bumbu** [comment]
Hi @rangitha 

That's strange, as I was testing the same behavior and it was working fine for me. 
I was testing on [inline demo](http://ariutta.github.io/svg-pan-zoom/demo/inline.html).

If it doesn't work like this for you then it may be a library bug, or some specific setup/code for your example. If you think that it's a bug, please open a new issue with some reproducible examples.

**Comment by nikhiljutla01** [comment]
Hi Bumbu ,
I have tried the above snippet for text selection , It worked as expected but I missed some of the existing functionality like moving images. Also zooming and movement is going hand in hand for bigger images. We are unable to use copy option after right click the selected text .
Please help us the above issues .
