### ISSUE TITLE
Publish v3.1.1 to npm

### ISSUE THREAD

**Issue by ariutta** [ariutta/svg-pan-zoom#82]
@bumbu, can you do this? Is there a way for us both to publish to npm?

I moved uniwheel to dependencies.

**Comment by bumbu** [comment]
I published new version on npm.
I added [your account](https://www.npmjs.com/~ariutta) (I hope it is yours) to the list of owners.
Now you should be able to do `npm publish` if you're logged in.

**Comment by ariutta** [comment]
Yeah, that's me. Thanks!
