### ISSUE TITLE
Custom zoom in ,zoom out button in svg pan zoom

### ISSUE THREAD

**Issue by deeypak** [ariutta/svg-pan-zoom#86]
Hi,

how to use zoom in,zoom out and reset functionality showed in svg-panzoom.js demo ,on click of my web page buttons like below show button,i want to do zoom and reset functionality on click of button 
<button id="reset" >reset</button>
<button id="zoomin" >reset</button>
<button id="zoomout" >reset</button>

**Comment by bumbu** [comment]
Sorry, but this is not a helping board. You should write only issues here.
There is an API available. There is even an example with what you're asking.

You can post such questions on StackOverflow with `svgpanzoom` tag (as it is mentioned in Readme).
