### ISSUE TITLE
Background image zoom as svg content

### ISSUE THREAD

**Issue by Vizzielli** [ariutta/svg-pan-zoom#91]
Hi,

I've a background image under my svg code.
The content of the svg code follows the background image.

It's possible to set that image, always under svg, that suffers the pan and zoom together with vector svg content?

I tried to place the image in the svg code (through Raphael.js), but I don't find soultion.

Thanks!

**Comment by bumbu** [comment]
If your question is how you can pan and zoom only a specific group (`<g>` element) in your SVG then you may take a look at `demo/layers.html`. The idea is that you can have multiple parent groups in SVG and interact with only one of them. 
So in your case you would want to place your background in one group, and the zoomable content in another one. Set CSS class for zoomable group similart to the one set in `viewportSelector` option (you can check the default value in Readme).

**Comment by Vizzielli** [comment]
I use Raphael.js, so it force me the code and I can't put into svg code any group.

So, I've pan-zoom ork correctly ith svg content, but I've no idea about how to have same pan/zoom for svg and also for background image.

That's the code:

		<style type="text/css">
			#content {
				background-image: url(img/background.png);
				background-repeat: no-repeat;
			}
		</style>
	</head>
	<body>
		<div id="content">
			
		</div>
		<script src="raphael-min.js"></script>
		<script src="map.js"></script>
	</body>

The script generate in #content div that:
http://prntscr.com/66msz9

As you can see, I've put the background image in CSS style.
Now, pan-zoom work correctly for SVG element, but background image should have equal pan-zoom as SVG element.

I think most correctly question can be: is possible to apply pan-zoom for all "div" content?

**Comment by bumbu** [comment]
> I think most correctly question can be: is possible to apply pan-zoom for all "div" content?
svg-pan-zoom does pan and zoom only SVG content. So everything that is outside of it is not touched.

You have few options:

1. Place background inside of SVG as an image but before initializing svg-pan-zoom
* Use it as a background for your DIV element, listen for pan and zoom events from svg-pan-zoom and update your background-size and background-position accordingly

I would go with first option as it is simplest and most straightforward.

**Comment by andrewboni** [comment]
@bumbu can you elaborate more on option #1? I'm in the same boat and am attempting to do this with no luck...

Code:
```svg
<svg 
  xmlns="http://www.w3.org/2000/svg"
  fill="url(#bgimage)"
  >
  <defs>
      <pattern id="bgimage" x="0" y="0" patternUnits="userSpaceOnUse" height="1" width="1">
          <image x="0" y="0" xlink:href="bg-pattern.svg"></image>
      </pattern>
...
```

Thanks!

**Comment by andrewboni** [comment]
As an example, see this JSFiddle that represents my setup: https://jsfiddle.net/eeetfqLd/

Notice the checkered background image on the container. As I pan/zoom the svg, I'd expect it to move and/or zoom in/out. Would love to hear your thoughts

**Comment by bumbu** [comment]
When I answered first question I thought about a non-repeating background. In that case you could just insert the image into SVG. That's what first answer was about. It could look like https://jsfiddle.net/eeetfqLd/1/

Here you have a repeating background. And right now I have no ideas how to do that in an efficient way. If I'll come up with any solution then I'll write it here.

**Comment by andrewboni** [comment]
Got it, okay. Would definitely love to see your solution, if you can manage. I'll post a solution here as well.
