### ISSUE TITLE
Find Text and highlight within SVG image 

### ISSUE THREAD

**Issue by arjSharma** [ariutta/svg-pan-zoom#93]
Hi,

I am trying to search on a particular word within a svg image using my browsers Ctrl + F find tool. My issue is it does not search any of the text within the svg image. Would I need to implement my own find tool or am I missing something?

Thanks,

Arjun

**Comment by bumbu** [comment]
Sorry, but it seems to be related to browsers and not svg-pan-zoom. You can post this question on StackOverflow

**Comment by arjSharma** [comment]
Hi Bumbu, Yes you're correct.
I find IE is the only browser with this problem, the others work fine when using their default find text feature. I have managed to find resolution for IE but I am having trouble interfacing with the svg-pan-zoom plugin. Question: Is it possible to place an svg image within an iframe and still have the ability to pan and zoom? Currently when I use an iframe, I get the "Cannot ge
 svg image within an iframe and still have the ability to pan and zoom? Currently when I use an iframe, I get the "Cannot get SVG" error.

Thanks

**Comment by bumbu** [comment]
Is this question related to previous one (with search)?
Iframe should be treated as a separate window, and if you have all the code contained in it I don't see why it would not work.

But if it is still not working then you can open a new issue for that. Also a jsfiddle example will increase chances to find a solution.

**Comment by arjSharma** [comment]
Thanks Bambu, I've managed to resolve it.
