### ISSUE TITLE
Redraw SVG image when window is resized.

### ISSUE THREAD

**Issue by arjSharma** [ariutta/svg-pan-zoom#94]
Hi, 
I am trying to get an SVG image to rescale accordingly when I resize a window, 
Would it be possible to redraw the svg when I resize the window?

Thanks,
Arjun

**Comment by bumbu** [comment]
What do you mean by _redraw the svg_?
Please check `demo/resize.html`. There is an API method `resize` that recomputes container sizes.

If you want your SVG to scale proportionally with your window then you'll have to call `zoom` or `zoomBy` by yourself.

**Comment by arjSharma** [comment]
Hi Bambu, Thanks for the reply.
The resize.html demo has helped with the resizing of the image when changing the window size.

However, when I change the window size and click on the "Reset" control on the bottom right of the image, the image resizes to fit the original window's dimension. How can I get the Reset button to rescale the image according to the current window's dimensions?

Thanks

**Comment by bumbu** [comment]
Now it is not possible to alter the `originalState` internal variable that keeps original zoom and pan. The only way to alter them is to destroy and reinit svg-pan-zoom. 
A better approach would be to create custom control buttons (there is an example in demos) and implement reset the way you need it.

**Comment by arjSharma** [comment]
Thanks very much Bumbu!
