### ISSUE TITLE
Initial scale

### ISSUE THREAD

**Issue by runxel** [ariutta/svg-pan-zoom#95]
It would be great to have a parameter for the initial scale.
I have the problem of to much white space at the moment, it looks weird.
(I first tried to mimic it with minZoom. Which doesn't work in this way, at the beginning without any scrolling it will show the initial scale of 1 anyway.)

**Comment by bumbu** [comment]
Most probably it is a problem with your SVG. If you use `fit: true` then plugin checks your SVG bounding box (sizes) and fits it accordingly.
But you can set `fit: false` and zoom at whatever zoom level you need right after plugin initialization.

**Comment by Avareto** [comment]
I think the problem here is that the SVG will be initial drawn with the default scale of 1. Than you have to call zoom(myCustomInitialScale) which results in flickering.

**Comment by bumbu** [comment]
If `fit: true` is set then the plugin will do the adjustments whenever it is called.
It is true that a flicker can happen, all depends on how you load your SVG and when you initialize the plugin. 

A simple workaround would be to _hide_ your SVG until plugin is initialized. You can _hide_ it with opacity.

**Comment by Avareto** [comment]
Thanks! How do I know if the plugin is initialized?
I am using the plugin for showing different svgs with more or less details depending on the zoom level, like zooming in a map. For this to work smoothly having an initial scale and position for the plugin (the one of the previous svg) is very helpful!

**Comment by bumbu** [comment]
It all depends how you load the library. 
If you simply added the library as a HTML script, then it should be available on DOM ready event.
If you use modules (like Require.js) then you have a callback when a specific library is loaded.

You initialize the plugin for a specific SVG with `svgPanZoom('#some-id')`, and when you do that, you can say that the plugin is initialized.
