### ISSUE TITLE
Error with stat_density2d, linetype = "blank"

### ISSUE THREAD

**Issue by ghotson** [ariutta/svg-pan-zoom#96]
When I make my ggplot with a stat_density2d layer, svgPanZoom throws and error if I set linetype to blank.

example code:
**Works**
> p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
> svgPanZoom(p)

**Doesn't Work**
> p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),linetype="blank",geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
> svgPanZoom(p)
Error in as.hexmode(strsplit(lty, "")[[1]]) : 
  'x' cannot be coerced to class "hexmode"

**Comment by bumbu** [comment]
Sorry but I have no idea what is ggplot and what does the code you provided.
I suppose these things generate some SVGs. If so then providing these SVGs would be of help.

Also posting an example on some public service like jsfiddle would speed up the process.

**Comment by ghotson** [comment]
Shoot, sorry, thought I was in the svgPanZoom github, not svg-pan-zoom. My bad.
