### ISSUE TITLE
Pan to a specific X & Y coordinates, center and zoom into that point.

### ISSUE THREAD

**Issue by arjSharma** [ariutta/svg-pan-zoom#97]
Hi,

I am trying to pan to a specific point in my svg image and have it centred.

I have a button which, when clicked calls a function to pan the image to a specific rectangle e.g the bottom rect in my code example below (x: 1000, y:20).

I have tried to use the method "pan({x:1000,y:20});" to get the image to pan to that specific set of coordinates. The result of using the method often places the desired rect off the screen.

Can anyone help with my problem?

Thanks,
Arjun

<svg >
		<g id="viewport" xmlns:xlink="http://www.w3.org/1999/xlink">
   		<rect x="0" y="0" width="20" height="20"/>
   		 <rect x="50" y="20" width="10"  height="20"/>
                 <rect x="1000" y="20" width="10"  height="30"/>
 </svg>

**Comment by arjSharma** [comment]
https://gist.github.com/arjSharma/cd86dfec9b7b74e694cc

**Comment by bumbu** [comment]
Please post this question on stackoverflow (set `svgpanzoom` tag to that question).
Also you'll have a better probability to receive an answer if you'll provide a working (or not working) example. Not just the SVG code, but the whole page and script that can be just opened in browser and played with (like jsfiddle.net)

**Comment by arjSharma** [comment]
Hi Bumbu, please see the fiddle at : http://jsfiddle.net/arjSharma/n6r55dp1/2/ and stackoverflow at http://stackoverflow.com/questions/28853055/pan-to-specific-x-and-y-coordinates-and-center-image-svg-pan-zoom
